import { useEffect,useMemo,useState } from "react";
import { Buildings } from "@phosphor-icons/react/Buildings";
import { Key } from "@phosphor-icons/react/Key";
import { ShieldCheck } from "@phosphor-icons/react/ShieldCheck";
import { UserPlus } from "@phosphor-icons/react/UserPlus";
import { WarningCircle } from "@phosphor-icons/react/WarningCircle";
import { X } from "@phosphor-icons/react/X";
import { AccountSetup,AccountTeams } from "../components/AccountSetup.jsx";
import { AssistantCompanySheet } from "../components/AssistantCompanySheet.jsx";
import { StaffAccessInvite } from "../components/StaffAccessInvite.jsx";
import { ActionToast,ConfirmActionSheet,DismissibleLayer,Empty,MutationFeedback,PageHead,SearchField,Status } from "../components/UI.jsx";
import { canApproveAccess,roleLabel } from "../lib/access.js";
import { accessStateLabel,loadSessionAccountActivity,loadStaffAccessDirectory,resolveCurrentAccessSessionId,setStaffWebsiteAccess,staffRoleLabel } from "../lib/staff-access.js";
import { subscribeSessionPresence } from "../lib/presence.js";
import { demoAccessRequests,demoUsers } from "../data/demo.js";
import "./access-review.css";
import "./access-invites.css";
import "./field-operations.css";
import "./staff-access.css";

const FILTERS=[["all","All people"],["not_enabled","Needs access"],["invited","Invited"],["active","Active"],["disabled","Disabled"]];
function initials(name="FSY"){return name.split(/\s+/).filter(Boolean).map(part=>part[0]).slice(0,2).join("").toUpperCase();}
function demoDirectory(){return demoUsers.filter(user=>user.roleKey!=="committee_viewer").map((user,index)=>({staffId:`demo-staff-${index+1}`,name:user.name,operationalRole:user.roleKey,email:user.email,companyIds:user.roleKey==="assistant_coordinator"?["demo-1","demo-2"]:[],companyNames:user.roleKey==="assistant_coordinator"?["Company 01","Company 02"]:[],userId:`demo-user-${index+1}`,accountEmail:user.email,accessEnabled:user.status==="Active",accessState:user.status==="Active"?"active":"not_enabled"}));}
function formatRelative(value){if(!value)return"Never signed in";const ms=Date.now()-new Date(value).getTime();if(!Number.isFinite(ms))return"Sign-in time unavailable";const minutes=Math.max(0,Math.floor(ms/60000));if(minutes<1)return"Signed in just now";if(minutes<60)return`Last signed in ${minutes}m ago`;const hours=Math.floor(minutes/60);if(hours<24)return`Last signed in ${hours}h ago`;const days=Math.floor(hours/24);return days<7?`Last signed in ${days}d ago`:`Last signed in ${new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value))}`;}
function AccountActivity({person,onlineUserIds,activityByUser}){if(!person.userId)return <span className="account-activity waiting">{person.accessState==="invited"?"Waiting for setup":"No account yet"}</span>;if(onlineUserIds.has(person.userId))return <span className="account-activity online"><i/>Online now</span>;return <span className="account-activity">{formatRelative(activityByUser.get(person.userId)?.lastSignInAt)}</span>;}
function CompanyScope({person}){if(person.operationalRole!=="assistant_coordinator")return <span className="staff-access-whole-session">Whole session</span>;if(!person.companyNames?.length)return <span className="company-chip-empty"><WarningCircle/>No companies yet</span>;return <span className="access-v2-scope">{person.companyNames.join(" · ")}</span>;}

function RequestReview({request,companies,onClose,onDecision}){const[companyIds,setCompanyIds]=useState(request.companyIds||[]);const[busy,setBusy]=useState("");const[error,setError]=useState("");const decide=async(status)=>{setBusy(status);setError("");try{await onDecision?.(request.id,status,{companyIds:request.role==="assistant_coordinator"?companyIds:[],committeeScope:request.committeeScope||[]});onClose();}catch(err){setError(err.message||"This request could not be reviewed.");}finally{setBusy("");}};return <DismissibleLayer open onClose={onClose} title="Review access request" sheet><div className="field-sheet"><button type="button" data-layer-close className="icon-button modal-close" onClick={onClose} aria-label="Close"><X/></button><span className="kicker">Access request</span><h2>{request.name}</h2><p>{request.email} · {roleLabel(request.role)}</p>{request.role==="assistant_coordinator"?<div className="company-picker">{companies.map(company=><label key={company.id} className={companyIds.includes(company.id)?"selected":""}><input type="checkbox" checked={companyIds.includes(company.id)} onChange={()=>setCompanyIds(current=>current.includes(company.id)?current.filter(id=>id!==company.id):[...current,company.id])}/><span>{company.displayName||company.name}</span></label>)}</div>:null}{error?<MutationFeedback tone="error">{error}</MutationFeedback>:null}<div className="field-sheet-actions"><button className="secondary" disabled={Boolean(busy)} onClick={()=>decide("rejected")}>{busy==="rejected"?"Rejecting…":"Reject"}</button><button className="primary" disabled={Boolean(busy)||(request.role==="assistant_coordinator"&&!companyIds.length)} onClick={()=>decide("approved")}>{busy==="approved"?"Approving…":"Approve"}</button></div></div></DismissibleLayer>;}

export function createInitialAccessRequests(){return demoAccessRequests;}
export function Access({requests=[],invites=[],currentRole="logistics_admin",currentCapabilities=[],onDecision,onRefreshRoster,onCreateInvite,onRevokeInvite,onCreateRecovery,roster=demoUsers,companies=[],teams=[],sessionId:requestedSessionId="",live=false,sessionName,companyLimit=4}){
 const[newAccount,setNewAccount]=useState(false);const[teamTarget,setTeamTarget]=useState(null);const[recoveryResult,setRecoveryResult]=useState(null);const[sessionId,setSessionId]=useState(requestedSessionId);const[directory,setDirectory]=useState(live?[]:demoDirectory());const[activityByUser,setActivityByUser]=useState(new Map());const[onlineUserIds,setOnlineUserIds]=useState(new Set());const[filter,setFilter]=useState("all");const[filterTouched,setFilterTouched]=useState(false);const[query,setQuery]=useState("");const[inviteTarget,setInviteTarget]=useState(null);const[companyTarget,setCompanyTarget]=useState(null);const[reviewRequest,setReviewRequest]=useState(null);const[busyId,setBusyId]=useState("");const[error,setError]=useState("");const[notice,setNotice]=useState("");const[confirmDisable,setConfirmDisable]=useState(null);const[confirmRevoke,setConfirmRevoke]=useState(null);const[undo,setUndo]=useState(null);const[undoBusy,setUndoBusy]=useState(false);const canManage=canApproveAccess(currentRole,currentCapabilities);
 const refresh=async(knownSessionId=sessionId)=>{if(!live)return directory;const resolved=knownSessionId||await resolveCurrentAccessSessionId();if(!sessionId)setSessionId(resolved);const[nextDirectory,nextActivity]=await Promise.all([loadStaffAccessDirectory(resolved),loadSessionAccountActivity(resolved)]);setDirectory(nextDirectory);setActivityByUser(nextActivity);return nextDirectory;};
 useEffect(()=>{if(!live)return;(requestedSessionId?Promise.resolve(requestedSessionId):resolveCurrentAccessSessionId()).then(id=>{setSessionId(id);return refresh(id);}).catch(err=>setError(err.message||"Website access could not be loaded."));},[live,requestedSessionId]);
 useEffect(()=>live&&sessionId?subscribeSessionPresence(sessionId,setOnlineUserIds):undefined,[live,sessionId]);
 const counts=useMemo(()=>Object.fromEntries(FILTERS.map(([key])=>[key,key==="all"?directory.length:directory.filter(item=>item.accessState===key).length])),[directory]);
 useEffect(()=>{if(filterTouched||!directory.length)return;const next=counts.not_enabled?"not_enabled":counts.invited?"invited":counts.active?"active":"disabled";setFilter(next);},[directory.length,counts,filterTouched]);
 const shown=useMemo(()=>{const text=query.trim().toLowerCase();return directory.filter(item=>(filter==="all"||item.accessState===filter)&&(!text||`${item.name} ${item.email} ${item.accountEmail} ${staffRoleLabel(item.operationalRole)} ${(item.companyNames||[]).join(" ")}`.toLowerCase().includes(text)));},[directory,filter,query]);
 const missingCompanyCount=directory.filter(person=>person.operationalRole==="assistant_coordinator"&&!person.companyIds?.length).length;
 const linkedUsers=new Set(directory.map(item=>item.userId).filter(Boolean));const independent=(roster||[]).filter(user=>user.active!==false&&user.status!=="Pending"&&!linkedUsers.has(user.userId||user.id));const pendingRequests=requests.filter(request=>request.status==="pending");const independentInvites=invites.filter(invite=>!invite.staff_id&&invite.status==="pending");
 const toggleAccess=async(person,enabled,{offerUndo=true}={})=>{if(!live){setDirectory(current=>current.map(item=>item.staffId===person.staffId?{...item,accessState:enabled?"active":"disabled",accessEnabled:enabled}:item));if(offerUndo)setUndo({person,enabled:!enabled,message:`${person.name}'s sign-in was ${enabled?"enabled":"disabled"}.`});return true;}setBusyId(person.staffId);setError("");setNotice("");try{await setStaffWebsiteAccess(person.staffId,enabled);await refresh();if(offerUndo)setUndo({person,enabled:!enabled,message:`${person.name}'s sign-in was ${enabled?"enabled":"disabled"}.`});return true;}catch(err){setError(err.message||"Website access could not be changed.");return false;}finally{setBusyId("");}};
 const undoAccess=async()=>{if(!undo?.person)return;setUndoBusy(true);try{await toggleAccess(undo.person,undo.enabled,{offerUndo:false});setUndo(null);}finally{setUndoBusy(false);}};
 const recovery=async(person)=>{if(!person.userId||!onCreateRecovery)return;setBusyId(person.staffId);setError("");try{const created=await onCreateRecovery(person.userId);if(created?.code)setRecoveryResult({...created,name:person.name});else setNotice(`Recovery access was prepared for ${person.name}.`);}catch(err){setError(err.message||"Recovery access could not be prepared.");}finally{setBusyId("");}};
 const revoke=async(person)=>{if(!person.inviteId||!onRevokeInvite)return;setBusyId(person.staffId);setError("");try{await onRevokeInvite(person.inviteId);await refresh();setNotice(`${person.name}'s pending invite was revoked.`);}catch(err){setError(err.message||"Invite could not be revoked.");}finally{setBusyId("");setConfirmRevoke(null);}};
 const afterCompanySave=async(staffId)=>{const rows=await refresh();return rows.find(item=>item.staffId===staffId)||null;};
 return <section className="page staff-access-page access-v2"><PageHead title="Access" sessionName={sessionName} description="Start with the person. Their FSY responsibility, company scope and website account stay together." action={canManage?<button className="primary access-v2-invite" onClick={()=>setNewAccount(true)}><UserPlus/>Invite person</button>:null}/>
 {!canManage?<div className="notice"><WarningCircle/><div><b>View only</b><p>A whole-session administrator is required to change website access.</p></div></div>:null}{error?<MutationFeedback tone="error">{error}</MutationFeedback>:null}{notice?<MutationFeedback>{notice}</MutationFeedback>:null}
 {missingCompanyCount?<button type="button" className="access-readiness-note" onClick={()=>{setFilter("all");setFilterTouched(true);setQuery("");}}><Buildings/><div><b>{missingCompanyCount} Assistant Coordinator{missingCompanyCount===1?" needs":"s need"} companies</b><p>Set responsibility first, then give website access.</p></div></button>:null}
 <div className="access-v2-controls"><SearchField value={query} onChange={setQuery} label="Search people and website access" placeholder="Name, email, responsibility or company"/><div className="access-v2-filters" role="group" aria-label="Filter people by website access">{FILTERS.map(([key,label])=><button type="button" key={key} className={filter===key?"active":""} onClick={()=>{setFilter(key);setFilterTouched(true);}}><span>{label}</span>{counts[key]?<b>{counts[key]}</b>:null}</button>)}</div></div>
 <article className="panel access-v2-directory"><div className="staff-access-intro"><div><span className="kicker">People & accounts</span><h2>{FILTERS.find(([key])=>key===filter)?.[1]}</h2><p>{query?`${shown.length} match${shown.length===1?"":"es"}`:`${shown.length} ${shown.length===1?"person":"people"} in this view`}</p></div></div>
 {shown.length?<div className="staff-access-list">{shown.map(person=>{const needsCompanies=person.operationalRole==="assistant_coordinator"&&!person.companyIds?.length;const rowBusy=busyId===person.staffId;return <div className={`staff-access-row ${needsCompanies?"needs-scope":""}`} key={person.staffId}><div className="staff-access-person"><span className="person-avatar">{initials(person.name)}</span><span><b>{person.name}</b><small>{person.accountEmail||person.email||"Email will be confirmed when access is given"}</small></span></div><div className="staff-access-responsibility"><small>{staffRoleLabel(person.operationalRole)}</small><CompanyScope person={person}/></div><div className="access-v2-account-state"><Status tone={person.accessState==="active"?"good":person.accessState==="invited"?"warn":"neutral"}>{accessStateLabel(person.accessState)}</Status><AccountActivity person={person} onlineUserIds={onlineUserIds} activityByUser={activityByUser}/></div><div className="staff-access-actions">{needsCompanies?<button className="primary" disabled={!canManage||rowBusy} onClick={()=>setCompanyTarget({person,continueToAccess:person.accessState==="not_enabled"})}><Buildings/>Set companies</button>:person.operationalRole==="assistant_coordinator"?<button className="secondary compact-button" disabled={!canManage||rowBusy} onClick={()=>setCompanyTarget({person,continueToAccess:false})}><Buildings/>Companies</button>:null}{person.accessState==="not_enabled"&&!needsCompanies?<button className="primary" disabled={!canManage||rowBusy} onClick={()=>setInviteTarget(person)}><UserPlus/>Give access</button>:null}{person.accessState==="invited"?<button className="primary" disabled={!canManage||rowBusy} onClick={()=>setInviteTarget(person)}>Setup link</button>:null}{person.accessState==="disabled"?<button className="primary" disabled={!canManage||rowBusy} onClick={()=>toggleAccess(person,true)}>Enable</button>:null}{person.userId?<button className="secondary compact-button" disabled={!canManage||rowBusy} onClick={()=>setTeamTarget(roster.find(user=>user.userId===person.userId)||{userId:person.userId,name:person.name,teamKeys:[]})}>Committees</button>:null}{person.accessState==="active"?<details className="staff-access-more"><summary>More</summary><div><button disabled={!canManage||rowBusy} onClick={()=>recovery(person)}><Key/>Recovery</button><button className="danger-text" disabled={!canManage||rowBusy} onClick={()=>setConfirmDisable(person)}>Disable sign-in</button></div></details>:person.accessState==="invited"?<details className="staff-access-more"><summary>More</summary><div><button className="danger-text" disabled={!canManage||rowBusy} onClick={()=>setConfirmRevoke(person)}>Revoke invite</button></div></details>:null}</div></div>;})}</div>:<Empty title={query?"No person found":"Nothing needs attention here"} text={query?"Try another name, email, responsibility or company.":"Choose another access state or invite a person."}/>}</article>
 {(pendingRequests.length||independentInvites.length||independent.length)?<details className="panel access-v2-exceptions"><summary><span><b>Independent accounts & older requests</b><small>{pendingRequests.length+independentInvites.length+independent.length} items outside the Staff-linked flow</small></span></summary><div>{pendingRequests.map(request=><div className="legacy-access-row" key={request.id}><span><b>{request.name}</b><small>Pending request · {roleLabel(request.role)}</small></span><button className="secondary" onClick={()=>setReviewRequest(request)}>Review</button></div>)}{independentInvites.map(invite=><div className="legacy-access-row" key={invite.id}><span><b>{invite.display_name||invite.email}</b><small>Setup pending · {roleLabel(invite.role)}</small></span><button className="secondary" onClick={()=>onRevokeInvite?.(invite.id)}>Revoke</button></div>)}{independent.map(user=><div className="legacy-access-row" key={user.id||user.userId||user.email}><span><b>{user.name}</b><small>{roleLabel(user.role||user.roleKey)} · {user.email}</small></span>{onCreateRecovery&&(user.userId||user.user_id)?<button className="secondary" onClick={()=>recovery({userId:user.userId||user.user_id,name:user.name,staffId:user.userId||user.user_id})}><Key/>Recovery</button>:null}</div>)}</div></details>:null}
 <div className="staff-access-lifecycle-note"><ShieldCheck weight="fill"/><div><b>Assignments remain the source of truth</b><p>Giving website access does not redefine a leader&apos;s FSY responsibility. Company and committee changes continue to follow the assigned responsibility.</p></div></div>
 {newAccount?<AccountSetup teams={teams} companies={companies} onCreate={onCreateInvite} onClose={()=>setNewAccount(false)}/>:null}{teamTarget?<AccountTeams user={teamTarget} sessionId={sessionId} teams={teams} onClose={()=>setTeamTarget(null)} onSaved={async()=>{await refresh();await onRefreshRoster?.();}}/>:null}{inviteTarget?<StaffAccessInvite staff={inviteTarget} onClose={()=>setInviteTarget(null)} onInvited={()=>refresh()}/>:null}{companyTarget?<AssistantCompanySheet staff={companyTarget.person} companies={companies} directory={directory} companyLimit={companyLimit} continueToAccess={companyTarget.continueToAccess} onClose={()=>setCompanyTarget(null)} onSaved={afterCompanySave} onContinue={person=>{setCompanyTarget(null);setInviteTarget(person);}}/>:null}{reviewRequest?<RequestReview request={reviewRequest} companies={companies} onClose={()=>setReviewRequest(null)} onDecision={onDecision}/>:null}
 {recoveryResult?<DismissibleLayer open onClose={()=>setRecoveryResult(null)} title="Recovery code" sheet><div className="headcount-create"><h2>Recovery for {recoveryResult.name}</h2><label>One-time code<input readOnly value={recoveryResult.code}/></label><p>Expires {new Date(recoveryResult.expiresAt).toLocaleString()}. Share only with the account owner.</p><button className="secondary" onClick={()=>setRecoveryResult(null)}>Done</button></div></DismissibleLayer>:null}
 {confirmDisable?<ConfirmActionSheet open title={`Disable ${confirmDisable.name}'s sign-in?`} description="Their FSY staff assignment stays unchanged." impact="They will not be able to use FSY Ops until website access is enabled again." confirmLabel="Disable sign-in" cancelLabel="Keep enabled" busy={busyId===confirmDisable.staffId} onClose={()=>setConfirmDisable(null)} onConfirm={async()=>{if(await toggleAccess(confirmDisable,false))setConfirmDisable(null);}}/>:null}
 {confirmRevoke?<ConfirmActionSheet open title={`Revoke ${confirmRevoke.name}'s setup link?`} description="The current invitation will stop working." impact="Their FSY responsibility stays unchanged. You can create a new setup link later." confirmLabel="Revoke invite" cancelLabel="Keep invite" busy={busyId===confirmRevoke.staffId} onClose={()=>setConfirmRevoke(null)} onConfirm={()=>revoke(confirmRevoke)}/>:null}
 <ActionToast message={undo?.message} onAction={undo?undoAccess:null} onDismiss={()=>setUndo(null)} busy={undoBusy}/></section>;
}
