import { useCallback,useEffect,useMemo,useState } from 'react';
import { CheckCircle } from '@phosphor-icons/react/CheckCircle';
import { Clock } from '@phosphor-icons/react/Clock';
import { WarningCircle } from '@phosphor-icons/react/WarningCircle';
import { supabase } from '../lib/supabase.js';
import { HEADCOUNT_STATUSES,summarizeHeadcount } from '../lib/headcount-roster.js';
import { ActionToast,ConfirmActionSheet,DismissibleLayer,PageHead,SearchField,MutationFeedback } from '../components/UI.jsx';
import { relativeFreshness } from '../lib/ux-errors.js';
import './headcount-roster.css';

const STATUS_LABEL = Object.fromEntries(HEADCOUNT_STATUSES);
const STATUS_ORDER = { missing:0, known_elsewhere:1, unresolved:2, present:3, not_expected:4 };
const FILTERS = [
 {value:'attention',label:'Needs attention'},
 {value:'all',label:'Everyone'},
 {value:'accounted',label:'Accounted for'},
];
function includesText(person,text){if(!text)return true;return [person.display_name,person.fsy_id,person.company_name,person.group_name,person.person_type].filter(Boolean).join(' ').toLowerCase().includes(text);}
function matchesFilter(person,filter){if(filter==='attention')return ['missing','known_elsewhere','unresolved'].includes(person.status);if(filter==='accounted')return ['present','known_elsewhere','not_expected'].includes(person.status);return true;}
function severityText(totals){if(totals.missing)return `${totals.missing} missing`;if(totals.known_elsewhere)return `${totals.known_elsewhere} elsewhere`;if(totals.unresolved)return `${totals.unresolved} not checked`;return 'Complete';}
function groupRows(people){const map=new Map();for(const person of people){const key=person.group_name||'Ungrouped';if(!map.has(key))map.set(key,{name:key,people:[]});map.get(key).people.push(person);}return [...map.values()].map(group=>({...group,totals:summarizeHeadcount(group.people)})).sort((a,b)=>{const ta=a.totals,tb=b.totals;const sa=ta.missing*100+ta.known_elsewhere*10+ta.unresolved;const sb=tb.missing*100+tb.known_elsewhere*10+tb.unresolved;return sb-sa||a.name.localeCompare(b.name,undefined,{numeric:true});});}

export function HeadcountRoster({sessionId,sessionName,currentRole,capabilities=[],legacy}) {
 const [data,setData]=useState({rounds:[],people:[]});const [roundId,setRoundId]=useState('');const [company,setCompany]=useState('all');
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('attention');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [creating,setCreating]=useState(false);const [label,setLabel]=useState('');const [editing,setEditing]=useState(null);const [status,setStatus]=useState('present');const [note,setNote]=useState('');const [limit,setLimit]=useState(60);const [confirmCompany,setConfirmCompany]=useState(false);const [confirmClose,setConfirmClose]=useState(false);const [lastUpdated,setLastUpdated]=useState('');const [clock,setClock]=useState(Date.now());const [undo,setUndo]=useState(null);const [undoBusy,setUndoBusy]=useState(false);
 const whole=['coordinator','logistics_admin','session_director'].includes(currentRole);const canRecord=capabilities.includes('headcount_record');
 const reload=useCallback(async()=>{const {data:next,error:err}=await supabase.rpc('get_headcount_roster_v4',{p_session_id:sessionId,p_round_id:roundId||null});if(err)throw err;setData(next||{rounds:[],people:[]});setLastUpdated(new Date().toISOString());return next||{rounds:[],people:[]};},[sessionId,roundId]);
 useEffect(()=>{let active=true;reload().catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));const timer=setInterval(()=>{if(document.visibilityState!=='hidden'&&!busy)reload().catch(()=>active&&setError('Head count could not refresh. What is on screen may be out of date.'));},12000);return()=>{active=false;clearInterval(timer);};},[reload,busy]);
 useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),15000);return()=>clearInterval(timer);},[]);
 const round=data.rounds.find(r=>r.id===roundId)||data.rounds[0];const people=data.people.filter(p=>p.round_id===round?.id);const totals=summarizeHeadcount(people);const closed=Boolean(round?.closes_at);
 const companyRows=useMemo(()=>{const map=new Map();for(const p of people){const key=p.company_id||'session';if(!map.has(key))map.set(key,{id:key,name:p.company_id?p.company_name:'Session staff & unassigned',people:[]});map.get(key).people.push(p);}return [...map.values()].map(row=>({...row,totals:summarizeHeadcount(row.people)})).sort((a,b)=>{const sa=a.totals.missing*100+a.totals.known_elsewhere*10+a.totals.unresolved;const sb=b.totals.missing*100+b.totals.known_elsewhere*10+b.totals.unresolved;return sb-sa||a.name.localeCompare(b.name,undefined,{numeric:true});});},[people]);
 useEffect(()=>{if(!whole&&companyRows.length===1&&company!==companyRows[0].id)setCompany(companyRows[0].id);},[whole,companyRows,company]);
 const selectedCompany=companyRows.find(c=>c.id===company);const scoped=selectedCompany?selectedCompany.people:people;const groups=useMemo(()=>selectedCompany?groupRows(scoped):[],[selectedCompany,scoped]);
 const visible=useMemo(()=>{const text=query.trim().toLowerCase();return scoped.filter(p=>matchesFilter(p,filter)&&includesText(p,text)).sort((a,b)=>(STATUS_ORDER[a.status]??9)-(STATUS_ORDER[b.status]??9)||String(a.group_name||'').localeCompare(String(b.group_name||''),undefined,{numeric:true})||a.display_name.localeCompare(b.display_name));},[scoped,query,filter]);
 useEffect(()=>setLimit(60),[query,filter,company,round?.id]);
 const run=async(key,rpc,args)=>{setBusy(key);setError('');try{const {error:err}=await supabase.rpc(rpc,args);if(err)throw err;await reload();return true;}catch(e){setError(e.message||'Could not save. Try again.');await reload().catch(()=>{});return false;}finally{setBusy('');}};
 const openRound=async(e)=>{e.preventDefault();if(await run('round','open_headcount_round_v3',{p_session_id:sessionId,p_label:label})){setCreating(false);setLabel('');setRoundId('');setCompany('all');setFilter('attention');}};
 const updatePerson=async(person,nextStatus,nextNote='',offerUndo=true)=>{const previous={status:person.status,note:person.note||''};const ok=await run(person.id,'set_headcount_person_v3',{p_id:person.id,p_status:nextStatus,p_revision:person.revision,p_note:nextNote||null});if(ok&&offerUndo){setUndo({id:person.id,name:person.display_name,previousStatus:previous.status,previousNote:previous.note,message:`${person.display_name} marked ${String(STATUS_LABEL[nextStatus]||nextStatus).toLowerCase()}.`});}return ok;};
 const savePerson=async(e)=>{e.preventDefault();if(await updatePerson(editing,status,note,true))setEditing(null);};
 const undoPerson=async()=>{if(!undo)return;const latest=data.people.find(item=>item.id===undo.id);if(!latest){setUndo(null);return;}setUndoBusy(true);setError('');try{const {error:err}=await supabase.rpc('set_headcount_person_v3',{p_id:latest.id,p_status:undo.previousStatus,p_revision:latest.revision,p_note:undo.previousNote||null});if(err)throw err;await reload();setUndo(null);}catch(err){setError(err.message||'This status changed again. Review the latest value before trying to undo.');setUndo(null);await reload().catch(()=>{});}finally{setUndoBusy(false);}};
 const singleCompany=!whole&&companyRows.length===1;
 const attentionCount=totals.missing+totals.known_elsewhere+totals.unresolved;
 const freshness=relativeFreshness(lastUpdated,clock);

 return <section className="page headcount-roster-page headcount-v10"><PageHead title="Head count" sessionName={sessionName} description={whole?'See urgent companies first, then resolve the people who still need attention.':singleCompany&&selectedCompany?`${selectedCompany.name} · resolve exceptions first, then confirm the rest.`:'Account for people in your assigned companies, with exceptions first.'} action={whole?<button className="primary" onClick={()=>setCreating(true)} disabled={data.rounds.some(r=>!r.closes_at)}>New round</button>:null}/>
 {error?<MutationFeedback tone="error">{error}<button className="text-action" onClick={()=>reload().then(()=>setError('')).catch(()=>setError('Head count could not refresh.'))}>Retry</button></MutationFeedback>:null}
 {creating?<form className="panel headcount-create" onSubmit={openRound}><label>What are you counting?<input required maxLength={80} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Lunch · Monday or Evening check"/></label><p>The roster is captured when the round opens. Later company changes do not rewrite this count.</p><div><button className="secondary" type="button" onClick={()=>setCreating(false)}>Cancel</button><button className="primary" disabled={Boolean(busy)}>Open round</button></div></form>:null}
 {loading?<p role="status">Loading head count…</p>:!round?<div className="panel headcount-create"><h2>No head count is open</h2><p>{whole?'Open a round when it is time to account for the session.':'A session leader will open the round. Your company will appear here automatically.'}</p></div>:<>
 <div className="headcount-round-picker"><label>Round<select value={round.id} onChange={e=>{setRoundId(e.target.value);setCompany('all');setFilter('attention');}}>{data.rounds.map(r=><option value={r.id} key={r.id}>{r.label} · {r.closes_at?'Closed':'Open'}</option>)}</select></label><span className={error?'stale':''}><Clock/>{closed?'Read only':freshness||'Connected'}</span></div>
 <div className="headcount-v10-summary" role="status"><div><span className="kicker">{attentionCount?'Needs attention':'Round status'}</span><strong>{attentionCount||totals.accounted}</strong><small>{attentionCount?`${totals.missing} missing · ${totals.known_elsewhere} elsewhere · ${totals.unresolved} not checked`:`${totals.accounted}/${totals.total} accounted for`}</small></div><div className="headcount-v10-progress"><span><b>{totals.accounted}/{totals.total}</b><small>accounted for</small></span><i><b style={{width:`${totals.total?Math.round(totals.accounted/totals.total*100):0}%`}}/></i></div></div>
 <div className={`headcount-workspace${singleCompany?' single-company':''}`}>
 {!singleCompany?<aside className="headcount-companies" aria-label="Company progress"><button className={company==='all'?'selected':''} onClick={()=>{setCompany('all');setFilter('attention');}}>{whole?'Whole session':'My companies'}<span>{totals.accounted}/{totals.total}</span></button>{companyRows.map(c=><button key={c.id} className={company===c.id?'selected':''} onClick={()=>{setCompany(c.id);setFilter('attention');}}><span>{c.name}<small>{severityText(c.totals)}</small></span><b>{c.totals.accounted}/{c.totals.total}</b></button>)}</aside>:null}
 <section className="headcount-people"><div className="headcount-people-head"><div><span className="kicker">{selectedCompany?'Company':'Session'}</span><h2>{selectedCompany?.name||(whole?'Whole session':'My companies')}</h2></div>{canRecord&&!closed&&selectedCompany&&selectedCompany.people.some(p=>p.status==='unresolved')?<button className="secondary" onClick={()=>setConfirmCompany(true)}>Confirm remaining present</button>:null}</div>
 {groups.length?<div className="headcount-group-strip" aria-label="Counselor group progress">{groups.map(group=><button key={group.name} type="button" className={group.totals.missing||group.totals.known_elsewhere||group.totals.unresolved?'attention':'complete'} onClick={()=>{setQuery(group.name==='Ungrouped'?'':group.name);setFilter('attention');}}><span><b>{group.name}</b><small>{severityText(group.totals)}</small></span><strong>{group.totals.accounted}/{group.totals.total}</strong></button>)}</div>:null}
 <div className="headcount-v10-tools"><SearchField label="Find participant or staff member" placeholder="Name, FSY ID or counselor group" value={query} onChange={setQuery}/><div className="headcount-v10-filters" role="group" aria-label="Head count view">{FILTERS.map(option=><button type="button" className={filter===option.value?'active':''} key={option.value} onClick={()=>setFilter(option.value)}>{option.label}{option.value==='attention'&&attentionCount?<b>{selectedCompany?selectedCompany.totals.missing+selectedCompany.totals.known_elsewhere+selectedCompany.totals.unresolved:attentionCount}</b>:null}</button>)}</div></div>
 <div className="headcount-person-list">{visible.slice(0,limit).map(p=><div className={`headcount-person state-${p.status}`} key={p.id}><span><b>{p.display_name}</b><small>{[p.person_type==='staff'?'Staff':p.fsy_id,p.group_name].filter(Boolean).join(' · ')}</small>{p.note?<small className="headcount-note">{p.note}</small>:null}{p.recorded_at?<small className="headcount-recorded">Updated {new Intl.DateTimeFormat(undefined,{hour:'numeric',minute:'2-digit'}).format(new Date(p.recorded_at))}</small>:null}</span><button className={`headcount-state ${p.status}`} disabled={!canRecord||closed||Boolean(busy)} onClick={()=>{setEditing(p);setStatus(p.status==='unresolved'?'present':p.status);setNote(p.note||'');}}>{STATUS_LABEL[p.status]||p.status}</button>{canRecord&&!closed&&p.status==='unresolved'?<button className="secondary headcount-quick-present" disabled={Boolean(busy)} aria-label={`Mark ${p.display_name} present`} onClick={()=>updatePerson(p,'present','',true)}><CheckCircle/>Present</button>:null}</div>)}</div>
 {!visible.length?<div className="empty-inline"><b>{filter==='attention'?'Nothing needs attention in this view':'No people match this view'}</b><span>{filter==='attention'?'Everyone here is accounted for.':'Clear the search or change the view.'}</span></div>:null}{visible.length>limit?<button className="secondary" onClick={()=>setLimit(n=>n+60)}>Show more · {visible.length-limit} remaining</button>:null}</section></div>
 {whole&&!closed?<div className="headcount-close"><p>{totals.missing+totals.unresolved?'Resolve missing and unchecked people before closing.':totals.known_elsewhere?'Everyone is accounted for. Review known-elsewhere notes, then close when ready.':'Everyone is accounted for. Close the round when this head count is finished.'}</p><button className="secondary" disabled={Boolean(busy)||Boolean(totals.missing+totals.unresolved)} onClick={()=>setConfirmClose(true)}>Close round</button></div>:null}
 </>}
 <details className="headcount-legacy"><summary>Earlier aggregate reports</summary><p>These reports keep their original totals. Individual presence was not recorded for everyone.</p>{legacy}</details>
 {editing?<DismissibleLayer open onClose={()=>!busy&&setEditing(null)} title="Update head count" sheet><form className="headcount-create" onSubmit={savePerson}><span className="kicker">Head count status</span><h2>{editing.display_name}</h2><p>{[editing.fsy_id,editing.group_name,editing.company_name].filter(Boolean).join(' · ')}</p>{error?<MutationFeedback tone="error">{error}</MutationFeedback>:null}<label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{HEADCOUNT_STATUSES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Location or reason<input value={note} onChange={e=>setNote(e.target.value)} required={['known_elsewhere','not_expected'].includes(status)} maxLength={240} placeholder="Operational detail only; do not add medical information"/></label><div><button type="button" className="secondary" onClick={()=>setEditing(null)} disabled={Boolean(busy)}>Cancel</button><button className="primary" disabled={Boolean(busy)}>Save status</button></div></form></DismissibleLayer>:null}
 {confirmCompany?<ConfirmActionSheet open title={`Confirm ${selectedCompany?.name || 'company'} present?`} description={`This marks ${selectedCompany?.people.filter(p=>p.status==='unresolved').length||0} unchecked people present. Existing missing and elsewhere reports stay unchanged.`} impact="Use this only after counselors have accounted for the people in the company." confirmLabel="Confirm present" cancelLabel="Review people" tone="warning" busy={busy==='company'} onClose={()=>setConfirmCompany(false)} onConfirm={async()=>{if(await run('company','confirm_headcount_company_v3',{p_round_id:round.id,p_company_id:selectedCompany.id==='session'?null:selectedCompany.id}))setConfirmCompany(false);}}/>:null}
 {confirmClose?<ConfirmActionSheet open title={`Close ${round?.label || 'this head count'}?`} description="The current round becomes read-only after it closes." impact={`${totals.accounted} of ${totals.total} people are accounted for. ${totals.known_elsewhere?`${totals.known_elsewhere} are recorded elsewhere.`:'No unresolved exceptions remain.'}`} confirmLabel="Close head count" cancelLabel="Keep open" busy={busy==='close'} onClose={()=>setConfirmClose(false)} onConfirm={async()=>{if(await run('close','close_headcount_round_v3',{p_round_id:round.id})){setConfirmClose(false);}}}/>:null}
 <ActionToast message={undo?.message} onAction={undo?undoPerson:null} onDismiss={()=>setUndo(null)} busy={undoBusy}/>
 </section>;
}
