import { useCallback,useEffect,useMemo,useState } from 'react';
import { supabase } from '../lib/supabase.js';
import { HEADCOUNT_STATUSES,summarizeHeadcount,searchHeadcount } from '../lib/headcount-roster.js';
import { DismissibleLayer,PageHead,SearchField,MutationFeedback } from '../components/UI.jsx';
import './headcount-roster.css';

export function HeadcountRoster({sessionId,sessionName,currentRole,capabilities=[],legacy}) {
 const [data,setData]=useState({rounds:[],people:[]});const [roundId,setRoundId]=useState('');const [company,setCompany]=useState('all');
 const [query,setQuery]=useState('');const [filter,setFilter]=useState('unresolved');const [error,setError]=useState('');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [creating,setCreating]=useState(false);const [label,setLabel]=useState('');const [editing,setEditing]=useState(null);const [status,setStatus]=useState('present');const [note,setNote]=useState('');const [limit,setLimit]=useState(60);const [confirmCompany,setConfirmCompany]=useState(false);
 const whole=['coordinator','logistics_admin','session_director'].includes(currentRole);const canRecord=capabilities.includes('headcount_record');
 const reload=useCallback(async()=>{const {data:next,error:err}=await supabase.rpc('get_headcount_roster_v4',{p_session_id:sessionId,p_round_id:roundId||null});if(err)throw err;setData(next||{rounds:[],people:[]});},[sessionId,roundId]);
 useEffect(()=>{let active=true;reload().catch(e=>active&&setError(e.message)).finally(()=>active&&setLoading(false));const timer=setInterval(()=>{if(document.visibilityState!=='hidden')reload().catch(e=>active&&setError(e.message));},12000);return()=>{active=false;clearInterval(timer);};},[reload]);
 const round=data.rounds.find(r=>r.id===roundId)||data.rounds[0];const people=data.people.filter(p=>p.round_id===round?.id);const totals=summarizeHeadcount(people);const closed=Boolean(round?.closes_at);
 const companyRows=useMemo(()=>{const map=new Map();for(const p of people){const key=p.company_id||'session';if(!map.has(key))map.set(key,{id:key,name:p.company_id?p.company_name:'Session staff & unassigned',people:[]});map.get(key).people.push(p);}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,undefined,{numeric:true}));},[data,round?.id]);
 const selectedCompany=companyRows.find(c=>c.id===company);const scoped=selectedCompany?selectedCompany.people:people;const visible=searchHeadcount(scoped,query,filter);
 useEffect(()=>setLimit(60),[query,filter,company,round?.id]);
 const run=async(key,rpc,args)=>{setBusy(key);setError('');try{const {error:err}=await supabase.rpc(rpc,args);if(err)throw err;await reload();return true;}catch(e){setError(e.message||'Could not save. Try again.');await reload().catch(()=>{});return false;}finally{setBusy('');}};
 const openRound=async(e)=>{e.preventDefault();if(await run('round','open_headcount_round_v3',{p_session_id:sessionId,p_label:label})){setCreating(false);setLabel('');setRoundId('');setCompany('all');setFilter('unresolved');}};
 const savePerson=async(e)=>{e.preventDefault();if(await run(editing.id,'set_headcount_person_v3',{p_id:editing.id,p_status:status,p_revision:editing.revision,p_note:note||null}))setEditing(null);};
 return <section className="page headcount-roster-page"><PageHead title="Head count" sessionName={sessionName} description={whole?'See who is accounted for, find exceptions, and follow each company.':'Account for the people in your assigned companies.'} action={whole?<button className="primary" onClick={()=>setCreating(true)} disabled={data.rounds.some(r=>!r.closes_at)}>New round</button>:null}/>
 {error?<MutationFeedback tone="error">{error}<button className="text-action" onClick={()=>reload().then(()=>setError('')).catch(e=>setError(e.message))}>Retry</button></MutationFeedback>:null}
 {creating?<form className="panel headcount-create" onSubmit={openRound}><label>What are you counting?<input required maxLength={80} value={label} onChange={e=>setLabel(e.target.value)} placeholder="Lunch · Monday or Evening check"/></label><p>The roster is captured now. Later company changes will not alter this round. Meal service records stay separate: receiving a meal does not prove someone is present now.</p><div><button className="secondary" type="button" onClick={()=>setCreating(false)}>Cancel</button><button className="primary" disabled={Boolean(busy)}>Open round</button></div></form>:null}
 {loading?<p role="status">Loading head count…</p>:!round?<div className="panel headcount-create"><h2>No roster count yet</h2><p>{whole?'Open a round to check participants and staff individually.':'A session leader will open a round. Your company roster will appear here.'}</p></div>:<>
 <div className="headcount-round-picker"><label>Round<select value={round.id} onChange={e=>{setRoundId(e.target.value);setCompany('all');setFilter('all');}}>{data.rounds.map(r=><option value={r.id} key={r.id}>{r.label} · {r.closes_at?'Closed':'Open'}</option>)}</select></label><span>{new Date(round.opens_at).toLocaleString()} · {closed?'Read only':'Updates every 12 seconds'}</span></div>
 <div className="headcount-totals" role="status"><strong>{totals.accounted} <small>/ {totals.total} accounted for</small></strong><span>{totals.present} present · {totals.missing} missing · {totals.unresolved} not checked</span></div>
 <div className="headcount-workspace"><aside className="headcount-companies" aria-label="Company progress"><button className={company==='all'?'selected':''} onClick={()=>setCompany('all')}>{whole?'Whole session':'My companies'}<span>{totals.accounted}/{totals.total}</span></button>{companyRows.map(c=>{const t=summarizeHeadcount(c.people);return <button key={c.id} className={company===c.id?'selected':''} onClick={()=>{setCompany(c.id);setFilter('all');}}><span>{c.name}<small>{t.missing?`${t.missing} missing`:t.unresolved?`${t.unresolved} not checked`:'Accounted for'}</small></span><b>{t.accounted}/{t.total}</b></button>;})}</aside>
 <section className="headcount-people"><div className="headcount-people-head"><h2>{selectedCompany?.name||(whole?'Whole session':'My companies')}</h2>{canRecord&&!closed&&selectedCompany&&selectedCompany.people.some(p=>p.status==='unresolved')?<button className="secondary" onClick={()=>setConfirmCompany(true)}>Confirm unchecked people present</button>:null}</div><SearchField label="Find participant or staff member" placeholder="Name, FSY ID, company or group" value={query} onChange={value=>{setQuery(value);if(value)setFilter('all');}}/><label className="headcount-filter">Show<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">Everyone</option>{HEADCOUNT_STATUSES.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label>
 <div className="headcount-person-list">{visible.slice(0,limit).map(p=><div className="headcount-person" key={p.id}><span><b>{p.display_name}</b><small>{[p.person_type==='staff'?'Staff':p.fsy_id,p.group_name,p.company_name].filter(Boolean).join(' · ')}</small>{p.note?<small>{p.note}</small>:null}</span><button className={`headcount-state ${p.status}`} disabled={!canRecord||closed||Boolean(busy)} onClick={()=>{setEditing(p);setStatus(p.status==='unresolved'?'present':p.status);setNote(p.note||'');}}>{HEADCOUNT_STATUSES.find(([s])=>s===p.status)?.[1]}</button>{canRecord&&!closed&&p.status==='unresolved'?<button className="secondary" disabled={Boolean(busy)} aria-label={`Mark ${p.display_name} present`} onClick={()=>run(p.id,'set_headcount_person_v3',{p_id:p.id,p_status:'present',p_revision:p.revision})}>Present</button>:null}</div>)}</div>
 {!visible.length?<p className="empty-inline">No people match this view. Choose Everyone or clear the search.</p>:null}{visible.length>limit?<button className="secondary" onClick={()=>setLimit(n=>n+60)}>Show more · {visible.length-limit} remaining</button>:null}</section></div>
 {whole&&!closed?<div className="headcount-close"><p>{totals.missing+totals.unresolved?'Resolve missing and unchecked people before closing.':'Everyone is accounted for. This round can be closed.'}</p><button className="secondary" disabled={Boolean(busy)||Boolean(totals.missing+totals.unresolved)} onClick={()=>run('close','close_headcount_round_v3',{p_round_id:round.id})}>Close round</button></div>:null}
 </>}
 <details className="headcount-legacy"><summary>Earlier aggregate reports</summary><p>These reports keep their original totals. Individual presence was not recorded for everyone.</p>{legacy}</details>
 {editing?<DismissibleLayer open onClose={()=>!busy&&setEditing(null)} title="Update head count" sheet><form className="headcount-create" onSubmit={savePerson}><h2>{editing.display_name}</h2><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}>{HEADCOUNT_STATUSES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Location or reason<input value={note} onChange={e=>setNote(e.target.value)} required={['known_elsewhere','not_expected'].includes(status)} maxLength={240} placeholder="Operational detail only; do not add medical information"/></label><div><button type="button" className="secondary" onClick={()=>setEditing(null)} disabled={Boolean(busy)}>Cancel</button><button className="primary" disabled={Boolean(busy)}>Save status</button></div></form></DismissibleLayer>:null}
 {confirmCompany?<DismissibleLayer open onClose={()=>setConfirmCompany(false)} title="Confirm company presence" sheet><div className="headcount-create"><h2>Have you checked everyone?</h2><p>This confirms {selectedCompany?.people.filter(p=>p.status==='unresolved').length} unchecked people are physically present. Existing missing or elsewhere reports will stay unchanged.</p><button className="primary" disabled={Boolean(busy)} onClick={async()=>{if(await run('company','confirm_headcount_company_v3',{p_round_id:round.id,p_company_id:selectedCompany.id==='session'?null:selectedCompany.id}))setConfirmCompany(false);}}>Yes, they are present</button><button className="secondary" onClick={()=>setConfirmCompany(false)}>Cancel</button></div></DismissibleLayer>:null}
 </section>;
}
