import { useEffect, useMemo, useState } from "react";
import { ArrowRight } from "@phosphor-icons/react/ArrowRight";
import { Bed } from "@phosphor-icons/react/Bed";
import { Buildings } from "@phosphor-icons/react/Buildings";
import { CheckCircle } from "@phosphor-icons/react/CheckCircle";
import { Clock } from "@phosphor-icons/react/Clock";
import { Plus } from "@phosphor-icons/react/Plus";
import { UserPlus } from "@phosphor-icons/react/UserPlus";
import { Empty, MutationFeedback, PageHead, SearchField, SegmentedControl } from "../components/UI.jsx";
import { loadStaff } from "../lib/operations.js";
import { hasCapability, loadHousingRooms } from "../lib/field-operations.js";
import { loadHousingAssignmentsV2 } from "../lib/housing-context.js";
import { loadHousingArrivalQueue, subscribeToHousingHandoff } from "../lib/housing-handoff.js";
import { AssignmentEditor, RoomDetail, RoomEditor, humanizeRole, initials, roomLocation, sexLabel, waitLabel } from "./HousingDialogsV4.jsx";
import "./field-operations.css";
import "./housing-handoff.css";

const collator = new Intl.Collator(undefined, { numeric: true, sensitivity: "base" });
const PERSON_BATCH = 60;
const ROOM_BATCH = 24;

export function Housing({ sessionId, participants = [], capabilities = [], sessionName }) {
  const canView=hasCapability(capabilities,"housing_view"); const canManage=hasCapability(capabilities,"housing_manage");
  const [rooms,setRooms]=useState([]);const [assignments,setAssignments]=useState([]);const [staff,setStaff]=useState([]);const [arrivalQueue,setArrivalQueue]=useState([]);
  const [roomQuery,setRoomQuery]=useState("");const [roomFilter,setRoomFilter]=useState("all");const [roomLimit,setRoomLimit]=useState(ROOM_BATCH);
  const [personQuery,setPersonQuery]=useState("");const [personStatus,setPersonStatus]=useState("arrivals");const [personType,setPersonType]=useState("all");const [personLimit,setPersonLimit]=useState(PERSON_BATCH);
  const [roomOpen,setRoomOpen]=useState(false);const [editingRoom,setEditingRoom]=useState(null);const [selectedRoom,setSelectedRoom]=useState(null);const [selected,setSelected]=useState(null);const [error,setError]=useState("");const [saved,setSaved]=useState("");const [now,setNow]=useState(Date.now());
  const reload=async()=>{if(!sessionId||!canView)return;const[nextRooms,nextAssignments,nextStaff,nextQueue]=await Promise.all([loadHousingRooms(sessionId),loadHousingAssignmentsV2(sessionId),loadStaff(sessionId),loadHousingArrivalQueue(sessionId)]);setRooms(nextRooms);setAssignments(nextAssignments);setStaff(nextStaff);setArrivalQueue(nextQueue);};
  useEffect(()=>{reload().catch((err)=>setError(err.message||"Unable to load Housing."));},[sessionId,canView]);
  useEffect(()=>{if(!sessionId||!canView)return undefined;return subscribeToHousingHandoff(sessionId,()=>reload().catch(()=>{}));},[sessionId,canView]);
  useEffect(()=>{const id=window.setInterval(()=>setNow(Date.now()),60000);return()=>window.clearInterval(id);},[]);
  const assignedByPerson=useMemo(()=>new Map(assignments.map((item)=>[`${item.personType}:${item.personId}`,item])),[assignments]);
  const allPeople=useMemo(()=>{const youth=participants.filter((p)=>p.isCurrent!==false&&p.serverEligibility?.eligible!==false&&p.attendanceStatus!=="confirmed_not_attending").map((p)=>({id:p.id,kind:"participant",name:p.fullName||"Participant",sex:String(p.sex||"").toLowerCase(),context:`Participant · ${p.unit||"Unit not recorded"}`}));const leaders=staff.filter((p)=>p.isCurrent!==false).map((p)=>({id:p.id,kind:"staff",name:p.name,sex:String(p.sex||"").toLowerCase(),context:`Staff · ${humanizeRole(p.operationalRole)} · ${p.unit||"Unit not recorded"}`}));return[...youth,...leaders].sort((a,b)=>collator.compare(a.name,b.name));},[participants,staff]);
  const waitingPeople=useMemo(()=>arrivalQueue.map((q)=>({id:q.participantId,kind:"participant",name:q.name,sex:String(q.sex||"").toLowerCase(),context:[q.fsyId,q.company,q.group,q.unit].filter(Boolean).join(" · ")||"Checked-in participant",queue:true,checkedInAt:q.checkedInAt,waitLabel:waitLabel(q.checkedInAt,now)})).sort((a,b)=>new Date(a.checkedInAt||0)-new Date(b.checkedInAt||0)),[arrivalQueue,now]);
  const assignedPeople=allPeople.filter((p)=>assignedByPerson.has(`${p.kind}:${p.id}`));const assignedCount=assignedPeople.length;const unassignedCount=Math.max(0,allPeople.length-assignedCount);const totalBeds=rooms.reduce((s,r)=>s+r.capacity,0);const occupied=rooms.reduce((s,r)=>s+r.occupancy,0);const openSpaces=Math.max(0,totalBeds-occupied);const openRooms=rooms.filter((r)=>r.occupancy<r.capacity).length;const fullRooms=rooms.length-openRooms;
  const filteredRooms=useMemo(()=>{const text=roomQuery.trim().toLowerCase();return rooms.filter((r)=>roomFilter==="all"||(roomFilter==="open"?r.occupancy<r.capacity:r.occupancy>=r.capacity)).filter((r)=>!text||`${r.name} ${r.building} ${r.floor}`.toLowerCase().includes(text)).sort((a,b)=>collator.compare(a.name,b.name));},[rooms,roomQuery,roomFilter]);
  const filteredPeople=useMemo(()=>{const text=personQuery.trim().toLowerCase();let base;if(personStatus==="arrivals")base=waitingPeople;else if(personStatus==="assigned")base=allPeople.filter((p)=>assignedByPerson.has(`${p.kind}:${p.id}`));else base=allPeople.filter((p)=>!assignedByPerson.has(`${p.kind}:${p.id}`));return base.filter((p)=>personStatus==="arrivals"||personType==="all"||p.kind===personType).filter((p)=>!text||`${p.name} ${p.context}`.toLowerCase().includes(text));},[personStatus,waitingPeople,allPeople,assignedByPerson,personType,personQuery]);
  const visibleRooms=filteredRooms.slice(0,roomLimit);const visiblePeople=filteredPeople.slice(0,personLimit);
  if(!canView)return <section className="page"><PageHead title="Housing" sessionName={sessionName} description="Housing access is assigned by an FSY administrator."/><article className="panel"><Empty icon={Bed} title="Housing is not in your access" text="Ask an administrator to add the Housing team to your account if this is part of your assignment."/></article></section>;
  return <section className="page housing-v4">
    <PageHead title="Housing" sessionName={sessionName} description="Registration checks people in. Housing receives checked-in participants automatically and assigns rooms from this queue." action={canManage?<button className="primary" onClick={()=>setRoomOpen(true)}><Plus/>Add room</button>:null}/>
    {error?<MutationFeedback tone="error">{error}</MutationFeedback>:null}{saved?<MutationFeedback>{saved}</MutationFeedback>:null}
    <div className={`housing-v4-handoff${waitingPeople.length?" attention":""}`}><div className="housing-v4-handoff-icon"><ArrowRight/></div><div><span className="kicker">Live handoff from Registration</span><h2>{waitingPeople.length?`${waitingPeople.length} checked-in participant${waitingPeople.length===1?" is":"s are"} waiting for a room`:"No checked-in participants are waiting"}</h2><p>{waitingPeople.length?"Oldest waiting participants appear first. This queue updates automatically as Registration checks people in and disappears as Housing assigns rooms.":"New arrivals will appear here automatically after check-in."}</p></div>{waitingPeople.length?<button type="button" className="secondary" onClick={()=>{setPersonStatus("arrivals");setPersonQuery("");}}>View queue</button>:null}</div>
    <div className="housing-v4-metrics"><article className={waitingPeople.length?"attention":""}><span>Arrivals waiting</span><strong>{waitingPeople.length.toLocaleString()}</strong><small>Checked in · no room yet</small></article><article><span>Assigned</span><strong>{assignedCount.toLocaleString()}</strong><small>Participants and staff</small></article><article><span>Open spaces</span><strong>{openSpaces.toLocaleString()}</strong><small>{openRooms} room{openRooms===1?"":"s"} with space</small></article><article><span>Rooms</span><strong>{rooms.length.toLocaleString()}</strong><small>{fullRooms} full · {openRooms} open</small></article></div>
    <details className="housing-v4-coverage"><summary><span><b>Overall housing coverage</b><small>{unassignedCount.toLocaleString()} people have no room across the full roster</small></span><span>+</span></summary><div><p>This broader number includes people who have not arrived yet and staff. Day-one work should normally start with <b>Arrivals waiting</b>, not the full roster.</p></div></details>
    <div className="housing-v4-layout">
      <article className="panel housing-v4-panel"><div className="housing-v4-panel-head"><div><span className="kicker">Rooms</span><h2>Room map</h2><p>{rooms.length?`${rooms.length} rooms · ${openRooms} with space · ${fullRooms} full`:"Add rooms before assignments begin."}</p></div><Buildings size={22}/></div><div className="housing-v4-toolbar rooms"><SearchField value={roomQuery} onChange={(v)=>{setRoomQuery(v);setRoomLimit(ROOM_BATCH);}} label="Search rooms" placeholder="Room, building or floor"/><label><span>Availability</span><select value={roomFilter} onChange={(e)=>{setRoomFilter(e.target.value);setRoomLimit(ROOM_BATCH);}}><option value="all">All rooms · {rooms.length}</option><option value="open">Spaces available · {openRooms}</option><option value="full">Full · {fullRooms}</option></select></label></div><div className="housing-v4-room-grid">{visibleRooms.map((r)=>{const open=Math.max(0,r.capacity-r.occupancy);return <button type="button" key={r.id} className="housing-v4-room-card" onClick={()=>setSelectedRoom(r)}><span><b>{r.name}</b><small>{roomLocation(r)}</small></span><span className="capacity"><strong>{r.occupancy}/{r.capacity}</strong><small>{open?`${open} open`:"Full"}</small></span><i><span style={{width:`${Math.min(100,(r.occupancy/Math.max(1,r.capacity))*100)}%`}}/></i><em>{r.sex?`${sexLabel(r.sex)} housing`:"Unrestricted"}</em></button>})}{!filteredRooms.length?<Empty icon={Bed} title={rooms.length?"No rooms match":"No rooms yet"} text={rooms.length?"Try another search or availability filter.":"Add the first room before assigning people."}/>:null}</div>{filteredRooms.length>visibleRooms.length?<button type="button" className="secondary housing-v4-more" onClick={()=>setRoomLimit((v)=>v+ROOM_BATCH)}>Show {Math.min(ROOM_BATCH,filteredRooms.length-roomLimit)} more rooms</button>:null}</article>
      <article className="panel housing-v4-panel housing-v4-people"><div className="housing-v4-panel-head"><div><span className="kicker">Assignments</span><h2>{personStatus==="arrivals"?"Arrivals waiting":personStatus==="needs"?"People needing rooms":"Assigned people"}</h2><p>{personStatus==="arrivals"?"Checked-in participants are handed here automatically from Registration.":personStatus==="needs"?"Use this broader list for pre-arrival planning and staff housing.":"Review or change existing room assignments."}</p></div><UserPlus size={22}/></div><div className="housing-v4-person-controls"><SearchField value={personQuery} onChange={(v)=>{setPersonQuery(v);setPersonLimit(PERSON_BATCH);}} label="Find person" placeholder="Search name or assignment"/><SegmentedControl label="Housing work" value={personStatus} onChange={(v)=>{setPersonStatus(v);setPersonLimit(PERSON_BATCH);}} options={[{value:"arrivals",label:"Arrivals waiting",count:waitingPeople.length},{value:"needs",label:"Need room",count:unassignedCount},{value:"assigned",label:"Assigned",count:assignedCount}]}/>{personStatus!=="arrivals"?<label className="housing-v4-type"><span>People</span><select value={personType} onChange={(e)=>{setPersonType(e.target.value);setPersonLimit(PERSON_BATCH);}}><option value="all">Everyone</option><option value="participant">Participants</option><option value="staff">Staff</option></select></label>:null}</div><div className="housing-v4-person-list">{visiblePeople.map((p)=>{const a=assignedByPerson.get(`${p.kind}:${p.id}`);return <button type="button" key={`${p.kind}:${p.id}`} disabled={!canManage} onClick={()=>canManage&&setSelected({person:p,assignment:a})}><span className="person-avatar">{initials(p.name)}</span><span className="copy"><b>{p.name}</b><small>{p.context}</small>{p.queue?<em><Clock/>{p.waitLabel}</em>:null}</span><span className="assignment">{a?<><b>{a.roomName}</b><small>{a.bedLabel?`Bed / key ${a.bedLabel}`:"Assigned"}</small></>:p.queue?<><b>Assign room</b><small>From Registration</small></>:<><b>Needs room</b><small>Not assigned</small></>}</span></button>})}{!filteredPeople.length?<Empty icon={CheckCircle} title={personStatus==="arrivals"?"No arrivals are waiting":"No people match this view"} text={personStatus==="arrivals"?"As Registration checks people in, anyone without a room will appear here automatically.":"Try another search or filter."}/>:null}</div>{filteredPeople.length>visiblePeople.length?<button type="button" className="secondary housing-v4-more" onClick={()=>setPersonLimit((v)=>v+PERSON_BATCH)}>Show {Math.min(PERSON_BATCH,filteredPeople.length-personLimit)} more</button>:null}</article>
    </div>
    {roomOpen?<RoomEditor sessionId={sessionId} onClose={()=>setRoomOpen(false)} onSaved={async()=>{await reload();setSaved("Room added.");}}/>:null}
    {editingRoom?<RoomEditor sessionId={sessionId} room={editingRoom} onClose={()=>setEditingRoom(null)} onSaved={async()=>{await reload();setSaved("Room updated.");}}/>:null}
    {selectedRoom?<RoomDetail room={selectedRoom} assignments={assignments} canManage={canManage} onClose={()=>setSelectedRoom(null)} onEdit={()=>{setEditingRoom(selectedRoom);setSelectedRoom(null);}}/>:null}
    {selected?<AssignmentEditor sessionId={sessionId} person={selected.person} rooms={rooms} currentAssignment={selected.assignment} onClose={()=>setSelected(null)} onSaved={async()=>{await reload();setSaved(`${selected.person.name} housing updated.`);}}/>:null}
  </section>;
}
