import { ParticipantExceptionForm } from "../components/ParticipantExceptionForm.jsx";
import { personIdentity } from "../lib/person-identity.js";
import "../components/operational-state.css";
import { searchPeople } from "../lib/person-search.js";
import { writeWorkspaceLocation } from "../lib/navigation.js";
import { useEffect, useMemo, useRef, useState } from "react";
import { IdentificationCard } from "@phosphor-icons/react/IdentificationCard";
import { UserCircle } from "@phosphor-icons/react/UserCircle";
import { UsersThree } from "@phosphor-icons/react/UsersThree";
import { X } from "@phosphor-icons/react/X";
import { ActionToast, DismissibleLayer, Empty, MutationFeedback, PageHead, SearchField, SegmentedControl, Status } from "../components/UI.jsx";
import { loadOperationalStructure, loadPersonPrivateDetails, loadStaff } from "../lib/operations.js";
import { operationalEligibility } from "../lib/registration.js";
import { NO_SHOW_CONFIRMATION_SOURCES } from "../lib/identity-arrival.js";
import { formatCount } from "../lib/cohort.js";
import { demoSession } from "../data/session.js";
import "./operations.css";

const ROLE_LABELS={counselor:"Counselor",assistant_coordinator:"Assistant coordinator",coordinator:"Coordinator",committee_member:"Committee member",logistics_admin:"Logistical administrator",session_director:"Session directing couple",other:"Other staff"};
function initials(name="FSY"){return name.split(/\s+/).filter(Boolean).map(part=>part[0]).slice(0,2).join("").toUpperCase();}
function prettyPrivateLabel(key){return key.replace(/_/g," ").replace(/\b\w/g,letter=>letter.toUpperCase());}
function goToWorkspace(destination){if(typeof window==="undefined")return;writeWorkspaceLocation(destination);window.dispatchEvent(new Event("popstate"));}

function PersonSheet({currentRole,onRefresh,selected,groupMap,companyMap,eligibility,staffGroup,staffCompanies,canManage,canManageAttendance,attendanceBusy,privateDetails,onAttendanceChange,onOpenAssignments,onOpenGroup,onClose}){
 if(!selected)return null;
 const person=selected.person;const participant=selected.kind==="participant";const name=participant?person.fullName:person.name;const group=participant?groupMap.get(person.groupId):staffGroup;const company=participant&&group?companyMap.get(group.companyId):null;const confirmedAbsent=participant&&(person.attendanceStatus==="confirmed_not_attending"||eligibility?.reason==="Confirmed not attending");
 return <DismissibleLayer open onClose={onClose} title={`${name} details`} sheet className="people-v2-detail-layer"><div className="people-v2-detail"><header><span className="person-avatar large">{initials(name)}</span><div><span className="kicker">{participant?"Participant":"Staff"}</span><h2>{name}</h2><p>{participant?[person.fsyId,company?.displayName||company?.name,group?.displayName||group?.name].filter(Boolean).join(" · "):[ROLE_LABELS[person.operationalRole]||person.operationalRole,...staffCompanies.map(item=>item.displayName||item.name)].filter(Boolean).join(" · ")}</p></div><button type="button" data-layer-close className="icon-button" onClick={onClose} aria-label="Close"><X/></button></header>
 {participant?<div className="people-v2-facts"><div><span>FSY ID</span><b>{person.fsyId||"Not assigned"}</b>{person.previousFsyIds?.length?<small>Previous: {person.previousFsyIds.join(", ")}</small>:null}</div><div><span>Counselor group</span><b>{group?.displayName||group?.name||"Not assigned"}</b></div><div><span>Company</span><b>{company?.displayName||company?.name||"Not assigned"}</b></div>{!eligibility?.ok?<div><span>Needs attention</span><b>{eligibility?.reason}</b></div>:null}<div><span>Age at session</span><b>{person.age??"Not recorded"}</b></div><div><span>Ward / branch</span><b>{person.unit||"Not recorded"}</b></div><div><span>Stake / district</span><b>{person.stake||"Not recorded"}</b></div></div>:<div className="people-v2-facts"><div><span>Responsibility</span><b>{ROLE_LABELS[person.operationalRole]||person.operationalRole}</b></div><div><span>Counselor group</span><b>{staffGroup?.displayName||"Not assigned"}</b></div><div><span>Companies</span><b>{staffCompanies.length?staffCompanies.map(item=>item.displayName||item.name).join(", "):"Not assigned"}</b></div><div><span>Ward / branch</span><b>{person.unit||"Not recorded"}</b></div></div>}
 {participant&&group?<div className="people-v31-related"><div><span>Related work</span><b>{group.displayName||group.name||"Counselor group"}</b><small>Open the live structure without losing this person as your return point.</small></div><button type="button" className="secondary" onClick={()=>onOpenGroup(person,group,company)}>Open in Groups</button></div>:null}
 {!participant&&canManage?<div className="people-v31-related"><div><span>Related work</span><b>Responsibilities & coverage</b><small>Change this person’s assignment in the one place that owns staff responsibilities.</small></div><button type="button" className="secondary" onClick={()=>onOpenAssignments(person)}>Open in Assignments</button></div>:null}
 {participant&&canManageAttendance?<div className={confirmedAbsent?"notice compact-notice":"notice green compact-notice"}><UsersThree/><div><b>{confirmedAbsent?"Confirmed not attending":"Attendance expectation"}</b><p>{confirmedAbsent?"The registration record is preserved, but this person is excluded from current operations.":"Use this only after an authorized source confirms the participant will not attend."}</p><button type="button" className="secondary compact-button" disabled={attendanceBusy} onClick={()=>onAttendanceChange(person,confirmedAbsent?"expected":"confirmed_not_attending")}>{attendanceBusy?"Saving…":confirmedAbsent?"Restore as expected":"Mark not attending"}</button></div></div>:null}
 {!participant&&canManage?<div className="notice compact-notice"><UsersThree/><div><b>Assignments stays the source of truth</b><p>People is for finding and understanding the person. Responsibility changes stay in Assignments.</p></div></div>:null}
 {canManage&&privateDetails?<details className="private-details"><summary>Contact & registration details</summary><div>{Object.entries(privateDetails).filter(([key,value])=>value&&!["participant_id","staff_id","session_id","updated_at"].includes(key)).map(([key,value])=><div key={key}><span>{prettyPrivateLabel(key)}</span><b>{String(value)}</b></div>)}</div></details>:canManage?<p className="form-hint">No additional private fields are stored for this person.</p>:<p className="form-hint">Sensitive registration details are limited to authorized roles.</p>}
 {participant&&currentRole==="session_director"?<ParticipantExceptionForm person={person} onSaved={onRefresh}/>:null}</div></DismissibleLayer>;
}

export function People({currentRole,onRefresh,companyIds=null,sessionId,participants=[],cohort,assignment=null,canManage=false,canManageAttendance=false,onSetAttendance,structureSettings={},selectedPersonId="",onSelectPerson,onClearSelectedPerson,sessionName=demoSession.name}){
 const [allStaff,setStaff]=useState([]);const [structure,setStructure]=useState({groups:[],companies:[]});const [tab,setTab]=useState("participants");const [query,setQuery]=useState("");const [roleFilter,setRoleFilter]=useState("all");const [selected,setSelected]=useState(null);const [privateDetails,setPrivateDetails]=useState(null);const [error,setError]=useState("");const [attendanceBusy,setAttendanceBusy]=useState(false);const [confirmingNoShow,setConfirmingNoShow]=useState(null);const [confirmationSource,setConfirmationSource]=useState("");const [confirmationDetails,setConfirmationDetails]=useState("");const [confirmationError,setConfirmationError]=useState("");const [toast,setToast]=useState(null);const returnFocusRef=useRef(null);
 const reload=async()=>{if(!sessionId)return;const[nextStaff,nextStructure]=await Promise.all([loadStaff(sessionId),loadOperationalStructure(sessionId)]);setStaff(nextStaff);setStructure(nextStructure);};
 useEffect(()=>{if(sessionId)reload().catch(err=>setError(err.message||"Unable to load people."));else setStructure({groups:assignment?.groups||[],companies:assignment?.companies||[]});},[sessionId,assignment]);
 const groupMap=useMemo(()=>new Map(structure.groups.map(group=>[group.id,group])),[structure.groups]);const companyMap=useMemo(()=>new Map(structure.companies.map(company=>[company.id,company])),[structure.companies]);
 const staff=useMemo(()=>allStaff.filter(person=>companyIds===null||(person.companyIds||[]).some(id=>companyIds.includes(id))||companyIds.includes(groupMap.get(person.counselorGroupId)?.companyId)),[allStaff,companyIds,groupMap]);
 const rows=useMemo(()=>{if(!query.trim())return [];const source=(tab==="staff"?staff:participants).filter(person=>tab!=="staff"||roleFilter==="all"||person.operationalRole===roleFilter);return searchPeople(source,query,person=>{const group=groupMap.get(person.groupId||person.counselorGroupId);return [group?.displayName,companyMap.get(group?.companyId)?.displayName,...(person.companyIds||[]).map(id=>companyMap.get(id)?.displayName)];}).slice(0,80);},[participants,staff,tab,query,roleFilter,groupMap,companyMap]);
 const openPerson=async(kind,person,event)=>{returnFocusRef.current=event?.currentTarget||null;onSelectPerson?.(person.id);setSelected({kind,person});setPrivateDetails(null);setError("");if(!canManage||!sessionId)return;try{setPrivateDetails(await loadPersonPrivateDetails(kind,person.id));}catch(err){setError(err.message||"Private registration details could not be loaded.");}};
 useEffect(()=>{if(!selectedPersonId)return;const candidates=[...participants,...staff];const person=candidates.find(item=>item.id===selectedPersonId);if(person&&selected?.person?.id!==person.id)openPerson(participants.some(item=>item.id===person.id)?"participant":"staff",person);},[selectedPersonId,participants,staff]);
 const closePerson=()=>{setSelected(null);setPrivateDetails(null);onClearSelectedPerson?.();};
 const closeNoShow=()=>{if(attendanceBusy)return;setConfirmingNoShow(null);setConfirmationSource("");setConfirmationDetails("");setConfirmationError("");};
 const saveAttendance=async(person,status,note="")=>{setAttendanceBusy(true);setError("");try{await onSetAttendance?.(person.id,status,note);setSelected(current=>current?.person?.id===person.id?{...current,person:{...current.person,attendanceStatus:status,attendanceNote:note}}:current);setToast(status==="confirmed_not_attending"?`${person.fullName} marked not attending.`:`${person.fullName} restored as expected.`);return true;}catch(err){setError(err.message||"Attendance status could not be saved.");return false;}finally{setAttendanceBusy(false);}};
 const changeAttendance=async(person,status)=>{if(status==="confirmed_not_attending"){setConfirmingNoShow(person);setConfirmationError("");return;}await saveAttendance(person,status);};
 const confirmNoShow=async()=>{if(!confirmingNoShow)return;if(!confirmationSource){setConfirmationError("Choose who confirmed that the participant is not coming.");return;}if(confirmationSource==="Other authorized confirmation"&&!confirmationDetails.trim()){setConfirmationError("Add a short note explaining the authorized confirmation source.");return;}const note=confirmationDetails.trim()?`${confirmationSource}: ${confirmationDetails.trim()}`:confirmationSource;if(await saveAttendance(confirmingNoShow,"confirmed_not_attending",note))closeNoShow();};
 const selectedGroup=selected?.kind==="participant"?groupMap.get(selected.person.groupId):null;const selectedEligibility=selected?.kind==="participant"?operationalEligibility(selected.person,structureSettings):null;const selectedStaffGroup=selected?.kind==="staff"?groupMap.get(selected.person.counselorGroupId):null;const selectedStaffCompanies=selected?.kind==="staff"?(selected.person.companyIds||[]).map(id=>companyMap.get(id)).filter(Boolean):[];
 const scopeCopy=companyIds===null?"Search the whole session directory.":companyIds.length===1?"Search people in your assigned company.":`Search people across your ${companyIds.length} assigned companies.`;
 const returnToPerson=(person)=>({view:"people",personId:person.id});
 const openAssignments=(person)=>goToWorkspace({view:"assignments",tab:"people",staffId:person.id,returnTo:returnToPerson(person)});
 const openGroup=(person,group,company)=>goToWorkspace({view:"groups",groupId:group?.id||"",companyId:company?.id||group?.companyId||"",returnTo:returnToPerson(person)});

 return <section className="page people-v2"><PageHead title="People" sessionName={sessionName} description="Find one participant or staff member, then open only the context you need."/>{error?<MutationFeedback tone="error">{error}</MutationFeedback>:null}
 <article className="panel people-v2-search-card"><div className="people-v2-search-head"><div><span className="kicker">Find someone</span><h2>Search people</h2><p>{scopeCopy}</p></div><IdentificationCard size={24}/></div><SegmentedControl label="People directory" value={tab} onChange={value=>{setTab(value);setQuery("");setRoleFilter("all");closePerson();}} options={[{value:"participants",label:"Participants"},{value:"staff",label:"Staff"}]}/><SearchField value={query} onChange={setQuery} label={tab==="staff"?"Search staff":"Search participants"} placeholder={tab==="staff"?"Name, role, company, ward or stake":"Name, FSY ID, company, group, ward or stake"} autoFocus/>{tab==="staff"?<label className="people-v2-role"><span>Role</span><select value={roleFilter} onChange={event=>setRoleFilter(event.target.value)}><option value="all">All staff roles</option>{Object.entries(ROLE_LABELS).map(([value,label])=><option value={value} key={value}>{label}</option>)}</select></label>:null}</article>
 {query.trim()?<article className="panel people-v2-results"><div className="panel-head"><div><span className="kicker">Results</span><h2>{rows.length} match{rows.length===1?"":"es"}</h2></div></div><div className="people-v2-list">{rows.map(person=>{const participant=tab==="participants";const name=participant?person.fullName:person.name;const group=participant?groupMap.get(person.groupId):groupMap.get(person.counselorGroupId);const company=participant&&group?companyMap.get(group.companyId):null;const eligibility=participant?operationalEligibility(person,structureSettings):null;const secondary=participant?[person.fsyId,company?.displayName||company?.name,group?.displayName||group?.name].filter(Boolean).join(" · ")||person.unit||"Participant":[ROLE_LABELS[person.operationalRole]||person.operationalRole,...(person.companyIds||[]).map(id=>companyMap.get(id)?.displayName||companyMap.get(id)?.name).filter(Boolean)].join(" · ");return <button type="button" key={person.id} onClick={event=>openPerson(participant?"participant":"staff",person,event)}><span className="person-avatar">{initials(name)}</span><span><b>{name}</b><small>{secondary}</small></span>{participant&&!eligibility.ok?<Status tone="warn">{eligibility.reason}</Status>:null}</button>;})}{!rows.length?<Empty icon={UserCircle} title="No one found" text="Try a shorter name, FSY ID, company, group, ward or stake."/>:null}</div></article>:<article className="people-v2-start"><UserCircle size={38}/><h2>Start with a name or FSY ID</h2><p>Normal records stay quiet. Exceptions appear only when they matter.</p>{cohort&&tab==="participants"?<small>{formatCount(cohort.eligible)} eligible youth in your current scope</small>:null}</article>}
 <PersonSheet currentRole={currentRole} onRefresh={onRefresh} selected={selected} groupMap={groupMap} companyMap={companyMap} eligibility={selectedEligibility} staffGroup={selectedStaffGroup} staffCompanies={selectedStaffCompanies} canManage={canManage} canManageAttendance={canManageAttendance} attendanceBusy={attendanceBusy} privateDetails={privateDetails} onAttendanceChange={changeAttendance} onOpenAssignments={openAssignments} onOpenGroup={openGroup} onClose={closePerson}/>
 {confirmingNoShow?<DismissibleLayer open onClose={closeNoShow} title="Confirm participant not attending" sheet className="people-confirm-modal"><div className="people-confirm-sheet"><span className="kicker">Arrival reconciliation</span><h2>Confirm not attending</h2><p>Keep the registration record, but remove this person from current operations only after an authorized source confirms they will not attend.</p><div className="people-confirm-person"><b>{confirmingNoShow.fullName}</b><small>{confirmingNoShow.unit||confirmingNoShow.stake||"Unit not recorded"}</small></div><label className="people-confirm-field"><span>Who confirmed this?</span><select value={confirmationSource} onChange={event=>{setConfirmationSource(event.target.value);setConfirmationError("");}}><option value="">Choose confirmation source</option>{NO_SHOW_CONFIRMATION_SOURCES.map(source=><option value={source} key={source}>{source}</option>)}</select></label><label className="people-confirm-field"><span>Short note <small>(optional unless Other)</small></span><textarea value={confirmationDetails} onChange={event=>setConfirmationDetails(event.target.value)} maxLength={240}/></label>{confirmationError?<MutationFeedback tone="error">{confirmationError}</MutationFeedback>:null}<div className="field-sheet-actions"><button type="button" className="secondary" disabled={attendanceBusy} onClick={closeNoShow}>Keep expected</button><button type="button" className="primary" disabled={attendanceBusy} onClick={confirmNoShow}>{attendanceBusy?"Saving…":"Confirm not attending"}</button></div></div></DismissibleLayer>:null}
 <ActionToast message={toast} onDismiss={()=>setToast(null)} autoDismissMs={4000}/>
 </section>;
}
