import { useEffect,useMemo,useState } from "react";
import { ArrowClockwise } from "@phosphor-icons/react/ArrowClockwise";
import { Check } from "@phosphor-icons/react/Check";
import { IdentificationCard } from "@phosphor-icons/react/IdentificationCard";
import { WarningCircle } from "@phosphor-icons/react/WarningCircle";
import { PersonName } from "../components/PersonPeek.jsx";
import { DismissibleLayer,Empty,MutationFeedback,SearchField,Status } from "../components/UI.jsx";
import { hasCapability } from "../lib/field-operations.js";
import { finalizeFsyIds,loadIdentityReadiness,loadIdentityRoster,loadOriginCodes,rebuildDraftFsyIds,updateBadgeName } from "../lib/identity-arrival.js";
import { searchPeople } from "../lib/person-search.js";
import { recoverableWriteError,usePendingPageGuard,useSingleFlight } from "../lib/reliable-action.js";
import "./registration-operations.css";

const FILTERS=[{value:"all",label:"All"},{value:"active",label:"Active IDs"},{value:"ready",label:"Ready for ID"},{value:"preferred",label:"Name review"},{value:"reprint",label:"Reprint"},{value:"origin",label:"Origin issue"}];
function initials(name="FSY"){return name.split(/\s+/).filter(Boolean).map(part=>part[0]).slice(0,2).join("").toUpperCase();}
function meaningfulPreferred(row){if(!row.preferredName)return false;const preferred=row.preferredName.trim().toLowerCase(),full=row.fullName.trim().toLowerCase(),first=row.fullName.trim().split(/\s+/)[0]?.toLowerCase()||"";return preferred&&preferred!==full&&preferred!==first;}
function readyForId(row){return Boolean(row.isCurrent&&row.verificationStatus==="verified"&&row.groupId&&!row.fsyId);}

export function IdentityFoundationV31({sessionId,capabilities=[],onChanged}){
 const canManage=hasCapability(capabilities,"identity_manage")||hasCapability(capabilities,"registration_manage");
 const runSingleFlight=useSingleFlight();
 const[readiness,setReadiness]=useState(null),[origins,setOrigins]=useState([]),[rows,setRows]=useState([]),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[busy,setBusy]=useState(false),[message,setMessage]=useState(null),[editing,setEditing]=useState(null),[badgeName,setBadgeName]=useState(""),[confirmingFinalize,setConfirmingFinalize]=useState(false);
 usePendingPageGuard(busy);
 const reload=async()=>{if(!sessionId)return;const[nextReadiness,nextOrigins,nextRows]=await Promise.all([loadIdentityReadiness(sessionId),loadOriginCodes(sessionId),loadIdentityRoster(sessionId)]);setReadiness(nextReadiness);setOrigins(nextOrigins);setRows(nextRows);};
 useEffect(()=>{reload().catch(error=>setMessage({tone:"error",text:error.message}));},[sessionId]);
 const counts=useMemo(()=>({all:rows.length,active:rows.filter(r=>Boolean(r.fsyId)).length,ready:rows.filter(readyForId).length,preferred:rows.filter(r=>r.nameReviewRequired).length,reprint:rows.filter(r=>r.needsReprint).length,origin:rows.filter(r=>!r.originCode&&Boolean(r.groupId)).length}),[rows]);
 const filtered=useMemo(()=>{let base=rows.filter(row=>filter==="all"||filter==="active"&&Boolean(row.fsyId)||filter==="ready"&&readyForId(row)||filter==="preferred"&&row.nameReviewRequired||filter==="reprint"&&row.needsReprint||filter==="origin"&&!row.originCode&&Boolean(row.groupId));return searchPeople(base,search,row=>[...(row.previousFsyIds||[]),row.originCode||""]).slice(0,300);},[rows,search,filter]);
 const prepared=Boolean(readiness?.draftIds||readiness?.finalizedIds),finalized=Boolean(readiness?.finalizedIds),originClear=Number(readiness?.unresolvedOrigin||0)===0;
 const prepare=async()=>runSingleFlight("identity-write",async()=>{setBusy(true);setMessage(null);try{const count=await rebuildDraftFsyIds(sessionId);await reload();await onChanged?.();setMessage({tone:"success",text:`${Number(count||0).toLocaleString()} draft FSY IDs prepared. Review identity issues before finalizing.`});}catch(error){setMessage({tone:"error",text:recoverableWriteError(error,"Draft FSY IDs could not be prepared.")});}finally{setBusy(false);}});
 const finalize=async()=>runSingleFlight("identity-write",async()=>{setBusy(true);setMessage(null);try{const count=await finalizeFsyIds(sessionId);await reload();await onChanged?.();setConfirmingFinalize(false);setMessage({tone:"success",text:`${Number(count||0).toLocaleString()} IDs finalized. Day-one changes now use the audited replacement workflow.`});}catch(error){setMessage({tone:"error",text:recoverableWriteError(error,"FSY IDs could not be finalized.")});}finally{setBusy(false);}});
 const saveBadgeName=async()=>{if(!editing||!badgeName.trim())return;return runSingleFlight("identity-write",async()=>{setBusy(true);setMessage(null);try{await updateBadgeName(editing.participantId,badgeName.trim());const name=editing.fullName;setEditing(null);setBadgeName("");await reload();await onChanged?.();setMessage({tone:"success",text:`${name}'s badge name was updated. The registration name was not changed.`});}catch(error){setMessage({tone:"error",text:recoverableWriteError(error,"The badge name could not be updated.")});}finally{setBusy(false);}});};
 if(!sessionId)return null;
 return <section className="ops-workspace identity-v31" aria-busy={busy}>
  <article className="panel identity-v31-head">
   <div className="identity-v31-title"><span className="kicker">FSY identities</span><h2>{finalized?"FSY IDs are finalized":"Prepare and review FSY IDs"}</h2><p>Only current, verified and grouped participants enter the active ID set.</p></div>
   <Status tone={finalized?"good":prepared?"warn":"muted"}>{finalized?"Finalized":prepared?"Draft ready":"Not prepared"}</Status>
   {canManage?<div className="identity-v31-actions"><button className="secondary" onClick={prepare} disabled={busy||finalized}><ArrowClockwise/>{readiness?.draftIds?"Rebuild draft":"Prepare IDs"}</button><button className="primary" onClick={()=>setConfirmingFinalize(true)} disabled={busy||!readiness?.draftIds||!originClear||finalized}><Check/>{finalized?"Finalized":"Finalize"}</button></div>:null}
  </article>
  {message?<MutationFeedback tone={message.tone}>{message.text}</MutationFeedback>:null}
  <div className="identity-v31-progress" aria-label="FSY ID progress"><span className={prepared?"done":"current"}><b>1</b><small>Prepare</small></span><span className={prepared&&originClear?"done":prepared?"current":""}><b>2</b><small>Review</small></span><span className={finalized?"done":prepared&&originClear?"current":""}><b>3</b><small>Finalize</small></span></div>
  <div className="identity-v31-summary" aria-label="FSY ID summary"><button type="button" onClick={()=>setFilter("active")} aria-pressed={filter==="active"}><b>{counts.active}</b><span>Active IDs</span></button><button type="button" onClick={()=>setFilter("ready")} aria-pressed={filter==="ready"}><b>{counts.ready}</b><span>Ready to issue</span></button><button type="button" onClick={()=>setFilter("preferred")} aria-pressed={filter==="preferred"}><b>{counts.preferred}</b><span>Name review</span></button><button type="button" onClick={()=>setFilter("reprint")} aria-pressed={filter==="reprint"}><b>{counts.reprint}</b><span>Reprint</span></button><button type="button" onClick={()=>setFilter("origin")} aria-pressed={filter==="origin"}><b>{counts.origin}</b><span>Origin issues</span></button></div>
  <article className="panel identity-v31-roster">
   <div className="identity-v31-roster-head"><div><span className="kicker">Participant identity</span><h2>IDs and badge names</h2><p>Search first, then narrow the list only when you need to.</p></div><IdentificationCard size={24}/></div>
   <div className="identity-v31-toolbar"><SearchField value={search} onChange={setSearch} label="Search FSY identities" placeholder="Participant name, FSY ID, ward, stake, company or group"/><div className="identity-v31-filters" role="group" aria-label="Identity filters">{FILTERS.map(item=><button type="button" key={item.value} className={filter===item.value?"active":""} onClick={()=>setFilter(item.value)}><span>{item.label}</span><b>{counts[item.value]}</b></button>)}</div></div>
   <div className="identity-v31-result"><span><b>{filtered.length}</b> shown{search?` for “${search}”`:""}</span>{filter!=="all"?<button type="button" className="text-action" onClick={()=>setFilter("all")}>Clear filter</button>:null}</div>
   <div className="identity-v31-table" role="table" aria-label="FSY identities"><div className="identity-v31-columns" role="row"><span>Participant</span><span>FSY ID</span><span>Company / group</span><span>Badge</span><span>Status</span></div>{filtered.map(row=>{const issue=row.needsReprint?"Reprint needed":row.nameReviewRequired?"Name review":!row.originCode&&row.groupId?"Origin issue":readyForId(row)?"Ready to issue":"Ready";return <div className={`identity-v31-row${issue!=="Ready"?" review":""}`} role="row" key={row.participantId}><div className="identity-v31-person"><span className="person-avatar">{initials(row.fullName)}</span><span><b><PersonName person={{...row,id:row.participantId}}/></b><small>{row.unit||"Unit not recorded"}{row.stake?` · ${row.stake}`:""}</small></span></div><div><small>FSY ID</small><b className="mono-id">{row.fsyId||"Not issued"}</b>{row.previousFsyIds?.length?<small>Previous: {row.previousFsyIds.join(", ")}</small>:null}</div><div><small>Company / group</small><b>{row.companyName||"Unassigned"}</b><span>{row.groupName||"No counselor group"}</span></div><div><small>Badge</small><button type="button" className="identity-v31-badge" disabled={!canManage||!row.fsyId||busy} onClick={()=>{setEditing(row);setBadgeName(row.badgeName||row.fullName);}}>{row.badgeName||row.fullName}</button></div><div className="identity-v31-state"><small>Status</small><Status tone={issue==="Ready"?"good":issue==="Ready to issue"?"neutral":"warn"}>{issue}</Status></div></div>})}{!filtered.length?<Empty icon={IdentificationCard} title="Nothing in this view" text="Clear the filter or try another search."/>:null}</div>
  </article>
  <details className="panel identity-v31-origins"><summary><span><b>Origin code registry</b><small>{origins.length} stake, district or mission codes</small></span><span>+</span></summary><div><p className="form-hint">Codes stay explicit so similar place names cannot silently share an identifier.</p><div className="origin-code-grid">{origins.map(origin=><div key={origin.code}><b>{origin.code}</b><span>{origin.name}</span><small>{origin.participantCount} participants{origin.aliases.length?` · aliases: ${origin.aliases.join(", ")}`:""}</small></div>)}</div></div></details>
  <DismissibleLayer open={Boolean(editing)} onClose={()=>{if(!busy){setEditing(null);setBadgeName("");}}} title="Edit badge name" sheet className="identity-badge-modal-v5">{editing?<div className="identity-badge-sheet-v5" aria-busy={busy}><header><span className="kicker">Badge name</span><h2>{editing.fullName}</h2><p>This changes the printed badge name only.</p></header><div className="identity-badge-context-v5"><span><small>FSY ID</small><b className="mono-id">{editing.fsyId}</b></span><span><small>Registered name</small><b>{editing.fullName}</b></span>{meaningfulPreferred(editing)?<span><small>Preferred name</small><b>{editing.preferredName}</b></span>:null}</div><label className="ops-confirm-field"><span>Badge name</span><input autoFocus value={badgeName} onChange={event=>setBadgeName(event.target.value)} disabled={busy}/></label><div className="ops-confirm-actions"><button className="secondary" onClick={()=>{setEditing(null);setBadgeName("");}} disabled={busy}>Cancel</button><button className="primary" onClick={saveBadgeName} disabled={busy||!badgeName.trim()}>{busy?"Saving…":"Save badge name"}</button></div></div>:null}</DismissibleLayer>
  <DismissibleLayer open={confirmingFinalize} onClose={()=>!busy&&setConfirmingFinalize(false)} title="Finalize FSY IDs" sheet><div className="ops-confirm-sheet" aria-busy={busy}><header><span className="kicker">Final step</span><h2>Finalize FSY IDs?</h2><p>Day-one changes will then use the audited vacancy and replacement workflow.</p></header><div className="ops-confirm-warning"><b>{readiness?.draftIds||0} draft IDs</b><span>will become final. Registration names remain unchanged.</span></div>{counts.origin?<p className="warning-copy"><WarningCircle/> {counts.origin} origin issue{counts.origin===1?"":"s"} must be resolved first.</p>:null}<div className="ops-confirm-actions"><button className="secondary" onClick={()=>setConfirmingFinalize(false)} disabled={busy}>Cancel</button><button className="primary" onClick={finalize} disabled={busy||counts.origin>0}>{busy?"Finalizing…":"Confirm finalization"}</button></div></div></DismissibleLayer>
 </section>;
}
