import { useEffect,useMemo,useRef,useState } from "react";
import { ArrowRight } from "@phosphor-icons/react/ArrowRight";
import { Check } from "@phosphor-icons/react/Check";
import { CloudArrowUp } from "@phosphor-icons/react/CloudArrowUp";
import { WarningCircle } from "@phosphor-icons/react/WarningCircle";
import { MutationFeedback,Status } from "../components/UI.jsx";
import { loadParticipants,loadSession } from "../lib/backend.js";
import { parseFinalRosterFile,resolveFinalRosterRecords } from "../lib/final-roster-import.js";
import { applyFinalRegistrationBaseline,loadFinalRegistrationBaseline,previewFinalRegistrationBaseline } from "../lib/final-roster.js";
import { recoverableWriteError,useSingleFlight } from "../lib/reliable-action.js";
import "./registration-final-v21.css";

function formatDate(value){if(!value)return"";return new Intl.DateTimeFormat(undefined,{dateStyle:"medium",timeStyle:"short"}).format(new Date(value));}
function statusLabel(value){return value==="approved"?"Approved":value==="awaiting"?"Awaiting approval":value==="cancelled"?"Cancelled":value;}
function impactItem(label,value,note=""){return <span><b>{Number(value||0).toLocaleString()}</b><small>{label}</small>{note?<em>{note}</em>:null}</span>;}

export function RegistrationFinalBaselineV22({sessionId,canManage=false,setImported,onChanged,onNavigate}){
 const input=useRef(null);
 const runSingleFlight=useSingleFlight();
 const[session,setSession]=useState(null),[baseline,setBaseline]=useState(null),[filename,setFilename]=useState(""),[result,setResult]=useState(null),[resolutions,setResolutions]=useState({}),[preview,setPreview]=useState(null),[confirmReset,setConfirmReset]=useState(false),[busy,setBusy]=useState(""),[message,setMessage]=useState(null);
 const refreshState=async()=>{if(!sessionId)return;const[nextSession,nextBaseline]=await Promise.all([loadSession(sessionId),loadFinalRegistrationBaseline(sessionId)]);setSession(nextSession);setBaseline(nextBaseline);};
 useEffect(()=>{refreshState().catch(error=>setMessage({tone:"error",text:error.message}));},[sessionId]);
 const conflicts=result?.identityConflicts||[];
 const unresolved=useMemo(()=>conflicts.filter(group=>!resolutions[group.id]),[conflicts,resolutions]);
 const suggested=useMemo(()=>conflicts.filter(group=>group.resolution==="merge").length,[conflicts]);
 const currentStep=!result?1:result.errors.length?2:unresolved.length?3:preview?5:4;
 const stepState=(step)=>step<currentStep?"done":step===currentStep?"current":"upcoming";
 const choose=async(file)=>{if(!file)return;return runSingleFlight("final-roster-action",async()=>{setBusy("read");setMessage(null);setPreview(null);setConfirmReset(false);setFilename(file.name);try{const next=await parseFinalRosterFile(file,{sessionStart:session?.starts_on||"2026-09-14",sessionEnd:session?.ends_on||"2026-09-19"});const defaults=Object.fromEntries(next.identityConflicts.filter(group=>group.resolution).map(group=>[group.id,group.resolution]));setResolutions(defaults);setResult(next);}catch(error){setResult(null);setMessage({tone:"error",text:error.message||"The final roster could not be read."});}finally{setBusy("");}});};
 const resetFile=()=>{if(busy)return;setFilename("");setResult(null);setResolutions({});setPreview(null);setConfirmReset(false);setMessage(null);if(input.current)input.current.value="";};
 const decide=(id,value)=>{if(busy)return;setResolutions(current=>({...current,[id]:value}));setPreview(null);setConfirmReset(false);};
 const previewImpact=async()=>{if(!result||result.errors.length||unresolved.length||!canManage)return;return runSingleFlight("final-roster-action",async()=>{setBusy("preview");setMessage(null);try{const resolved=await resolveFinalRosterRecords(result,resolutions);const impact=await previewFinalRegistrationBaseline({sessionId,records:resolved.records});setPreview({impact,resolved});setMessage({tone:"success",text:"Server preview passed. Review the production impact before applying the final roster."});}catch(error){setPreview(null);setMessage({tone:"error",text:recoverableWriteError(error,"The final roster could not be previewed safely.")});}finally{setBusy("");}});};
 const apply=async()=>{if(!preview?.resolved?.records?.length||!confirmReset||!canManage)return;return runSingleFlight("final-roster-action",async()=>{setBusy("apply");setMessage(null);try{const summary=await applyFinalRegistrationBaseline({sessionId,sourceFilename:filename,sourceSha256:result.sourceSha256,records:preview.resolved.records});if(setImported)setImported(await loadParticipants(sessionId));await onChanged?.();await refreshState();setFilename("");setResult(null);setResolutions({});setPreview(null);setConfirmReset(false);if(input.current)input.current.value="";setMessage({tone:"success",text:`Final roster applied: ${Number(summary.participant_count||0).toLocaleString()} youth and ${Number(summary.staff_count||0).toLocaleString()} counselor records. Rehearsal structure and roster-derived activity were cleared so the real structure can be built fresh.`});}catch(error){setMessage({tone:"error",text:recoverableWriteError(error,"The final roster was not applied. No partial baseline should be kept.")});}finally{setBusy("");}});};
 return <section className="final-roster-v22" aria-busy={Boolean(busy)}>
  {message?<MutationFeedback tone={message.tone}>{message.text}</MutationFeedback>:null}
  <div className="final-roster-v22-head"><div><span className="kicker">Final FSY roster</span><h2>{baseline?"Final baseline is active":"Confirm the final source roster"}</h2><p>The safety checks are unchanged. This view shows one decision at a time.</p></div><Status tone={baseline?"good":"warn"}>{baseline?"Final baseline active":"Not finalized"}</Status></div>
  {baseline?<div className="final-roster-v22-current"><span><b>{Number(baseline.recordCount||0).toLocaleString()}</b><small>records</small></span><span><b>{Number(baseline.participantCount||0).toLocaleString()}</b><small>participants</small></span><span><b>{Number(baseline.staffCount||0).toLocaleString()}</b><small>counselors</small></span><p>Applied {formatDate(baseline.createdAt)} · {baseline.sourceFilename}</p></div>:null}
  <ol className="final-roster-v22-steps" aria-label="Final roster progress">{[[1,"Upload"],[2,"Validate"],[3,"Identity matches"],[4,"Impact"],[5,"Apply"]].map(([step,label])=><li key={step} className={stepState(step)} aria-current={step===currentStep?"step":undefined}><span>{step<currentStep?<Check weight="bold"/>:step}</span><b>{label}</b></li>)}</ol>

  {currentStep===1?<article className="panel final-roster-v22-stage"><div className="panel-head"><div><span className="kicker">1 · Upload</span><h2>{baseline?"Replace the final baseline":"Choose the complete final export"}</h2><p>Participant + Counselor CSV or Excel only. Nothing changes while the file is checked.</p></div></div><button type="button" className="dropzone final-roster-v22-dropzone" disabled={!canManage||Boolean(busy)} onClick={()=>input.current?.click()}><CloudArrowUp size={30}/><b>{busy==="read"?"Checking file…":"Choose final CSV or Excel file"}</b><span>Dates, statuses, session ages and possible re-registrations are checked before production is touched.</span></button><input ref={input} hidden type="file" accept=".csv,.xlsx,.xls" disabled={Boolean(busy)} onChange={event=>choose(event.target.files?.[0])}/></article>:null}

  {currentStep===2&&result?<article className="panel final-roster-v22-stage"><div className="panel-head"><div><span className="kicker">2 · Validate</span><h2>{result.errors.length} blocking file issue{result.errors.length===1?"":"s"}</h2><p>{result.summary.total.toLocaleString()} source registrations were read from {filename}.</p></div><Status tone="danger">Fix file first</Status></div><div className="final-roster-v22-source-summary">{impactItem("participants",result.summary.participants)}{impactItem("counselors",result.summary.staff)}{impactItem("approved",result.summary.approved)}{impactItem("awaiting",result.summary.awaiting)}{impactItem("cancelled",result.summary.cancelled)}</div><div className="error-list">{[...result.errors,...result.warnings].slice(0,20).map((issue,index)=><p key={`${issue.row}-${issue.field}-${index}`}><b>Row {issue.row}:</b> {issue.message}{issue.severity==="warning"?" · review recommended":""}</p>)}</div><div className="panel-actions"><span>Correct the source file, then upload it again.</span><button type="button" className="secondary" disabled={Boolean(busy)} onClick={resetFile}>Choose another file</button></div></article>:null}

  {currentStep===3&&result?<article className="panel final-roster-v22-stage"><div className="panel-head"><div><span className="kicker">3 · Identity matches</span><h2>{unresolved.length} decision{unresolved.length===1?"":"s"} remaining</h2><p>{suggested?`${suggested} strong re-registration match${suggested===1?" was":"es were"} preselected. `:""}Decide only the identities that still need a human judgment.</p></div><Status tone="warn">{unresolved.length} unresolved</Status></div><div className="final-roster-v21-conflict-list">{conflicts.map((group,index)=><div className={`final-roster-v21-conflict${resolutions[group.id]?" resolved":""}`} key={group.id}><div className="final-roster-v21-conflict-head"><span><b>{group.rows[0]?.fullName||`Possible duplicate ${index+1}`}</b><small>{group.reason}</small></span><Status tone={resolutions[group.id]?"good":"warn"}>{resolutions[group.id]==="merge"?"Use latest registration":resolutions[group.id]==="keep"?"Keep separate":"Decision needed"}</Status></div><div className="final-roster-v21-conflict-rows">{group.rows.map(row=><span key={row.row}><b>{statusLabel(row.registrationStatus)}</b><small>{row.unit||"Unit missing"} · {row.registeredAtRaw||row.registeredAt}</small></span>)}</div><div className="final-roster-v21-conflict-actions"><button type="button" disabled={Boolean(busy)} className={resolutions[group.id]==="merge"?"primary":"secondary"} onClick={()=>decide(group.id,"merge")}>Same person · use latest</button><button type="button" disabled={Boolean(busy)} className={resolutions[group.id]==="keep"?"primary":"secondary"} onClick={()=>decide(group.id,"keep")}>Different people · keep both</button></div></div>)}</div><div className="panel-actions"><button type="button" className="secondary" disabled={Boolean(busy)} onClick={resetFile}>Choose another file</button><span>{unresolved.length?"Finish the identity decisions to continue.":"Identity review complete."}</span></div></article>:null}

  {currentStep===4&&result?<article className="panel final-roster-v22-stage"><div className="panel-head"><div><span className="kicker">4 · Production impact</span><h2>File checks passed</h2><p>Review the source summary, then ask the server to calculate exactly what would be preserved and reset.</p></div><Status tone="good">Ready for preview</Status></div><div className="final-roster-v22-source-summary">{impactItem("participants",result.summary.participants)}{impactItem("counselors",result.summary.staff)}{impactItem("approved",result.summary.approved)}{impactItem("awaiting",result.summary.awaiting)}{impactItem("cancelled",result.summary.cancelled)}{impactItem("ages recalculated",result.summary.ageAdjusted)}</div>{result.warnings.length?<details className="final-roster-v22-warnings"><summary>{result.warnings.length} validation warning{result.warnings.length===1?"":"s"}</summary><div className="error-list">{result.warnings.slice(0,16).map((issue,index)=><p key={`${issue.row}-${issue.field}-${index}`}><b>Row {issue.row}:</b> {issue.message}</p>)}</div></details>:null}<div className="final-roster-v22-file"><span><small>Source file</small><b>{filename}</b></span><span><small>Identity review</small><b>{conflicts.length?`${conflicts.length} matching group${conflicts.length===1?"":"s"} reviewed`:"No identity conflicts"}</b></span></div><div className="panel-actions"><button type="button" className="secondary" disabled={Boolean(busy)} onClick={resetFile}>Choose another file</button><button type="button" className="primary" disabled={!canManage||Boolean(busy)} onClick={previewImpact}>{busy==="preview"?"Checking production…":"Preview production impact"}<ArrowRight/></button></div></article>:null}

  {currentStep===5&&preview?<article className="panel final-roster-v22-stage"><div className="panel-head"><div><span className="kicker">5 · Apply</span><h2>Production impact is understood</h2><p>The final write is one database transaction. If a safety assertion fails, the baseline rolls back.</p></div><Status tone="good">Server preview passed</Status></div><div className="final-roster-v22-source-summary">{impactItem("final participants",preview.impact.participant_count)}{impactItem("final counselors",preview.impact.staff_count)}{impactItem("existing youth matched",preview.impact.matched_participants)}{impactItem("existing staff matched",preview.impact.matched_staff)}{impactItem("manual leaders preserved",preview.impact.manual_staff_preserved)}{impactItem("linked accounts preserved",preview.impact.account_links_preserved)}</div><div className="final-roster-v21-reset-note"><WarningCircle/><span><b>What becomes fresh</b><small>{Number(preview.impact.companies_to_reset||0)} rehearsal companies · {Number(preview.impact.groups_to_reset||0)} counselor groups · {Number(preview.impact.badges_to_reset||0)} test IDs · {Number(preview.impact.checkins_to_reset||0)} check-ins. Staff-to-company and counselor-to-group assignments are cleared. Housing room inventory stays, but rehearsal room assignments are cleared.</small></span></div><label className="final-roster-v21-confirm"><input type="checkbox" checked={confirmReset} disabled={Boolean(busy)} onChange={event=>setConfirmReset(event.target.checked)}/><span><b>Make this file the final registration baseline</b><small>I understand that Access/accounts remain while rehearsal roster-derived operations are reset.</small></span></label><div className="panel-actions"><button type="button" className="secondary" disabled={Boolean(busy)} onClick={()=>setPreview(null)}>Back to impact</button><button type="button" className="primary" disabled={!confirmReset||Boolean(busy)} onClick={apply}>{busy==="apply"?"Applying final baseline…":"Apply final roster"}<Check/></button></div></article>:null}

  {baseline&&!result?<div className="final-roster-v21-next"><span><Check weight="bold"/><b>Final registration is ready.</b><small>Build counselor groups and companies next, then assign counselors and Assistant Coordinators from the refreshed Staff roster.</small></span><button type="button" className="primary" disabled={Boolean(busy)} onClick={()=>onNavigate?.({view:"groups"})}>Build groups & companies<ArrowRight/></button></div>:null}
 </section>;
}
