import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowRight } from "@phosphor-icons/react/ArrowRight";
import { WarningCircle } from "@phosphor-icons/react/WarningCircle";
import { X } from "@phosphor-icons/react/X";
import { PersonName } from "../components/PersonPeek.jsx";
import { DismissibleLayer, MutationFeedback, PageHead, SearchField, Status } from "../components/UI.jsx";
import { formatCount } from "../lib/cohort.js";
import { loadPersonPrivateDetails } from "../lib/operations.js";
import { searchPeople } from "../lib/person-search.js";
import { operationalAgeRange } from "../lib/registration.js";
import { buildRegistrationReview, REVIEW_QUEUE_META, REVIEW_QUEUE_ORDER, reviewFlags } from "../lib/review.js";

function initials(person){return `${person.firstName?.[0]||""}${person.lastName?.[0]||""}`||"?";}
function ReviewDetail({selected,queue,ageRange,selectedFlags,groupChoice,setGroupChoice,busy,canManage,canVerify,privateBusy,privateDetails,closeSelected,verify,assign,onNavigate}){
 if(!selected)return <div className="quality-detail-empty"><WarningCircle size={34}/><h2>Select a person</h2><p>Open one record to see exactly why it needs review and what the safe next step is.</p></div>;
 const eligibilityReason=selected.serverEligibility?.reason||`Configured planning range ${ageRange.min}–${ageRange.max}`;
 return <><div className="quality-detail-head"><div><span className="kicker">Review record</span><h2><PersonName person={selected}/></h2><p>{selected.preferredName&&selected.preferredName!==selected.fullName?`Preferred name: ${selected.preferredName}`:"Original registration name"}</p></div><button type="button" data-layer-close className="icon-button" aria-label="Close review details" onClick={closeSelected}><X/></button></div>
 <div className="quality-detail-facts"><div className="quality-fact-combined"><span>Age & sex</span><b>{selected.age??"Not recorded"} · {selected.sex||"Not recorded"}</b></div><div><span>Registration</span><b>{selected.registrationStatus||"Unknown"}</b></div><div><span>Operational eligibility</span><b>{eligibilityReason}</b></div><div><span>Verification</span><b>{selected.verificationStatus||"Unknown"}</b></div><div><span>Ward / branch</span><b>{selected.unit||"Missing"}</b></div><div><span>Counselor group</span><b>{selected.groupId?"Assigned":"Not assigned"}</b></div><div><span>Source</span><b>{selected.sourceKind==="on_site"?"Added on-site":"Imported"}</b></div></div>
 <div className="quality-reasons"><span className="kicker">Why this person appears here</span>{selectedFlags.map((flag)=><div key={flag}><b>{REVIEW_QUEUE_META[flag].label}</b><small>{REVIEW_QUEUE_META[flag].help}</small></div>)}</div>
 {selectedFlags.includes("age_review")?<div className="notice compact-notice"><WarningCircle/><div><b>{eligibilityReason}</b><p>The server applies the FSY session-date rule. Keep the source record intact. If an authorized exception is needed, a Session Directing Couple can record it from Solutions after the required checks.</p></div></div>:null}
 {selectedFlags.includes("not_attending")?<div className="notice compact-notice"><WarningCircle/><div><b>Source registration preserved</b><p>This youth is excluded from check-in, grouping eligibility and head-count expectations until an authorized leader restores them.</p></div></div>:null}
 {selectedFlags.includes("awaiting")?<div className="notice compact-notice"><WarningCircle/><div><b>Awaiting source approval</b><p>A newer official export can approve this same record. If the participant arrives before that happens, send them to Solutions. A Session Directing Couple may record an authorized session decision without rewriting the official source status.</p>{onNavigate?<button type="button" className="secondary" onClick={()=>onNavigate({view:"registration",mode:"roster",filter:"awaiting"})}>Open Awaiting in Solutions<ArrowRight/></button>:null}</div></div>:null}
 {queue==="unassigned"&&(selected.compatibleGroups||[]).length>0&&groupChoice&&setGroupChoice&&canManage?<div className="quality-assign-box"><label>Assign counselor group<select value={groupChoice[selected.id]||""} onChange={(event)=>setGroupChoice({...groupChoice,[selected.id]:event.target.value})}><option value="">Choose compatible group</option>{(selected.compatibleGroups||[]).map((group)=><option key={group.id} value={group.id}>{group.displayName||group.name} · {group.memberCount} youth</option>)}</select></label><button className="primary" disabled={busy==="assign"||!groupChoice[selected.id]} onClick={assign}>{busy==="assign"?"Assigning…":"Assign participant"}</button></div>:null}
 {queue==="verification"&&selected.sourceKind==="on_site"&&canVerify?<div className="inline-actions quality-verify-actions"><button className="secondary" disabled={busy==="verify"} onClick={()=>verify(false)}>Reject addition</button><button className="primary" disabled={busy==="verify"} onClick={()=>verify(true)}>Verify participant</button></div>:null}
 {canManage?<details className="quality-private-details"><summary>Imported registration details</summary>{privateBusy?<p>Loading…</p>:privateDetails?<div>{privateDetails.date_of_birth?<div><span>Date of birth</span><b>{privateDetails.date_of_birth}</b></div>:null}{privateDetails.phone?<div><span>Phone</span><b>{privateDetails.phone}</b></div>:null}{privateDetails.contact_1_phone?<div><span>Parent / guardian phone</span><b>{privateDetails.contact_1_phone}</b></div>:null}</div>:<p>No additional private fields are stored for this participant.</p>}</details>:null}</>;
}

export function RegistrationReviewInbox({imported=[],groups=[],onVerify,onAssign,live=false,canManage=true,canVerify=false,structureSettings={},sessionName,onNavigate}){
 const review=useMemo(()=>buildRegistrationReview(imported,structureSettings),[imported,structureSettings]);const ageRange=operationalAgeRange(structureSettings);const firstNonEmpty=REVIEW_QUEUE_ORDER.find((key)=>review.counts[key]>0)||"awaiting";const[queue,setQueue]=useState(firstNonEmpty);const[search,setSearch]=useState("");const[visible,setVisible]=useState(20);const[selectedId,setSelectedId]=useState("");const[privateDetails,setPrivateDetails]=useState(null);const[privateBusy,setPrivateBusy]=useState(false);const[groupChoice,setGroupChoice]=useState({});const[busy,setBusy]=useState("");const[message,setMessage]=useState("");const returnFocusRef=useRef(null);const[isMobile,setIsMobile]=useState(()=>typeof window!=="undefined"&&window.matchMedia("(max-width: 700px)").matches);
 useEffect(()=>{if(!review.queues[queue]?.length&&review.queues[firstNonEmpty]?.length)setQueue(firstNonEmpty);},[firstNonEmpty,queue,review.queues]);
 useEffect(()=>{const media=window.matchMedia("(max-width: 700px)");const update=()=>setIsMobile(media.matches);update();media.addEventListener?.("change",update);return()=>media.removeEventListener?.("change",update);},[]);
 const rows=useMemo(()=>searchPeople(review.queues[queue]||[],search,(person)=>[person.registrationId||""]),[review,queue,search]);
 const rawSelected=imported.find((person)=>person.id===selectedId)||null;const selected=rawSelected&&queue==="unassigned"?{...rawSelected,compatibleGroups:groups.filter((group)=>group.sex===rawSelected.sex)}:rawSelected;const selectedFlags=selected?reviewFlags(selected,structureSettings):[];
 const closeSelected=()=>{setSelectedId("");setPrivateDetails(null);};const switchQueue=(key)=>{setQueue(key);setSearch("");setVisible(20);closeSelected();setMessage("");};
 const openPerson=async(person,event)=>{returnFocusRef.current=event?.currentTarget||null;setSelectedId(person.id);setPrivateDetails(null);setMessage("");if(!live||!canManage)return;setPrivateBusy(true);try{setPrivateDetails(await loadPersonPrivateDetails("participant",person.id));}catch{setPrivateDetails(null);}finally{setPrivateBusy(false);}};
 const verify=async(approved)=>{if(!selected||!onVerify)return;setBusy("verify");setMessage("");try{await onVerify(selected.id,approved);closeSelected();setMessage(approved?"Participant verified. They can now move to assignment if otherwise eligible.":"On-site addition rejected and retained in the audit history.");}catch(error){setMessage(error.message||"Unable to save verification.");}finally{setBusy("");}};
 const assign=async()=>{if(!selected||!onAssign||!groupChoice[selected.id])return;setBusy("assign");setMessage("");try{await onAssign(selected.id,groupChoice[selected.id]);closeSelected();setMessage(`${selected.fullName} was assigned to a counselor group.`);}catch(error){setMessage(error.message||"Unable to assign this participant.");}finally{setBusy("");}};
 const detailProps={selected,queue,ageRange,selectedFlags,groupChoice,setGroupChoice,busy,canManage,canVerify,privateBusy,privateDetails,closeSelected,verify,assign,onNavigate};
 return <section className="page registration-review-page"><PageHead title="Preflight review" sessionName={sessionName} description="See the people behind each exception, understand what is blocking them, and use the correct source or Solutions workflow."/>{message?<MutationFeedback>{message}</MutationFeedback>:null}<article className="panel quality-review-summary"><div className="panel-head"><div><span className="kicker">Attention first</span><h2>{formatCount(review.totalUnique)} people need review</h2><p>Queues can overlap; this headline counts each person once.</p></div><Status tone={review.totalUnique?"warn":"good"}>{review.totalUnique?"Preflight work":"Clear"}</Status></div><div className="quality-queue-grid" role="group" aria-label="Review queues">{REVIEW_QUEUE_ORDER.map((key)=>{const meta=REVIEW_QUEUE_META[key];return <button type="button" key={key} aria-pressed={queue===key} className={queue===key?"quality-queue-card active":"quality-queue-card"} onClick={()=>switchQueue(key)}><strong>{review.counts[key]}</strong><span>{meta.label}</span><small>{meta.short}</small></button>;})}</div><p className="quality-queue-hint">Choose a queue to see its next safe action.</p></article>
 <div className="quality-review-layout"><article className="panel quality-review-list"><div className="panel-head"><div><span className="kicker">{REVIEW_QUEUE_META[queue].label}</span><h2>{formatCount(review.counts[queue])} record{review.counts[queue]===1?"":"s"}</h2><p>{REVIEW_QUEUE_META[queue].help}</p></div></div><SearchField value={search} onChange={(value)=>{setSearch(value);setVisible(20);}} label="Search review records" placeholder="Name, preferred name, FSY context, ward, stake or registration ID"/><div className="quality-person-list">{rows.slice(0,visible).map((person)=><button type="button" key={person.id} className={selectedId===person.id?"quality-person-row selected":"quality-person-row"} onClick={(event)=>openPerson(person,event)}><span className="person-avatar">{initials(person)}</span><span><b><PersonName person={person}/></b><small>Age {person.age??"?"} · {person.unit||"Ward/branch missing"}{person.stake?` · ${person.stake}`:""}</small></span><Status tone={["age_review","cancelled","not_attending"].includes(queue)?"warn":"muted"}>{queue==="age_review"?(person.serverEligibility?.reason||`${person.age??"?"} yrs`):REVIEW_QUEUE_META[queue].label}</Status></button>)}{!rows.length?<div className="empty-inline"><b>No records in this queue</b><span>Nothing currently needs this type of review.</span></div>:null}</div>{rows.length>visible?<button type="button" className="secondary show-more" onClick={()=>setVisible((value)=>value+20)}>Show 20 more · {rows.length-visible} remaining</button>:null}</article>{!isMobile?<aside className={selected?"panel quality-person-detail open":"panel quality-person-detail"}><ReviewDetail {...detailProps}/></aside>:null}</div>{isMobile?<DismissibleLayer open={Boolean(selected)} onClose={closeSelected} title={selected?`${selected.fullName} review details`:"Review details"} className="quality-review-mobile-layer" sheet restoreFocusRef={returnFocusRef}><ReviewDetail {...detailProps}/></DismissibleLayer>:null}</section>;
}
