import { useEffect,useMemo,useState } from "react";
import { ArrowClockwise } from "@phosphor-icons/react/ArrowClockwise";
import { Check } from "@phosphor-icons/react/Check";
import { IdentificationCard } from "@phosphor-icons/react/IdentificationCard";
import { WarningCircle } from "@phosphor-icons/react/WarningCircle";
import { PersonName } from "../components/PersonPeek.jsx";
import { DismissibleLayer,Empty,MutationFeedback,SearchField,Status } from "../components/UI.jsx";
import { hasCapability } from "../lib/field-operations.js";
import { finalizeFsyIds,loadIdentityReadiness,loadIdentityRoster,loadOriginCodes,rebuildDraftFsyIds,updateBadgeName } from "../lib/identity-arrival.js";
import { searchPeople } from "../lib/person-search.js";
import "./registration-operations.css";

const FILTERS=[{value:"all",label:"All"},{value:"active",label:"Active IDs"},{value:"ready",label:"Ready for ID"},{value:"preferred",label:"Preferred name"},{value:"reprint",label:"Needs reprint"},{value:"origin",label:"Origin issue"}];
function initials(name="FSY"){return name.split(/\s+/).filter(Boolean).map(part=>part[0]).slice(0,2).join("").toUpperCase();}
function meaningfulPreferred(row){if(!row.preferredName)return false;const preferred=row.preferredName.trim().toLowerCase(),full=row.fullName.trim().toLowerCase(),first=row.fullName.trim().split(/\s+/)[0]?.toLowerCase()||"";return preferred&&preferred!==full&&preferred!==first;}
function readyForId(row){return Boolean(row.isCurrent&&row.verificationStatus==="verified"&&row.groupId&&!row.fsyId);}

export function IdentityFoundationV28({sessionId,capabilities=[],onChanged}){
 const canManage=hasCapability(capabilities,"identity_manage")||hasCapability(capabilities,"registration_manage");
 const[readiness,setReadiness]=useState(null),[origins,setOrigins]=useState([]),[rows,setRows]=useState([]),[search,setSearch]=useState(""),[filter,setFilter]=useState("all"),[busy,setBusy]=useState(false),[message,setMessage]=useState(null),[editing,setEditing]=useState(null),[badgeName,setBadgeName]=useState(""),[confirmingFinalize,setConfirmingFinalize]=useState(false);
 const reload=async()=>{if(!sessionId)return;const[nextReadiness,nextOrigins,nextRows]=await Promise.all([loadIdentityReadiness(sessionId),loadOriginCodes(sessionId),loadIdentityRoster(sessionId)]);setReadiness(nextReadiness);setOrigins(nextOrigins);setRows(nextRows);};
 useEffect(()=>{reload().catch(error=>setMessage({tone:"error",text:error.message}));},[sessionId]);
 const counts=useMemo(()=>({all:rows.length,active:rows.filter(r=>Boolean(r.fsyId)).length,ready:rows.filter(readyForId).length,preferred:rows.filter(r=>r.nameReviewRequired).length,reprint:rows.filter(r=>r.needsReprint).length,origin:rows.filter(r=>!r.originCode&&Boolean(r.groupId)).length}),[rows]);
 const filtered=useMemo(()=>{let base=rows.filter(row=>filter==="all"||filter==="active"&&Boolean(row.fsyId)||filter==="ready"&&readyForId(row)||filter==="preferred"&&row.nameReviewRequired||filter==="reprint"&&row.needsReprint||filter==="origin"&&!row.originCode&&Boolean(row.groupId));return searchPeople(base,search,row=>[...(row.previousFsyIds||[]),row.originCode||""]).slice(0,300);},[rows,search,filter]);
 const prepared=Boolean(readiness?.draftIds||readiness?.finalizedIds),finalized=Boolean(readiness?.finalizedIds),originClear=Number(readiness?.unresolvedOrigin||0)===0;
 const prepare=async()=>{setBusy(true);setMessage(null);try{const count=await rebuildDraftFsyIds(sessionId);await reload();await onChanged?.();setMessage({tone:"success",text:`${Number(count||0).toLocaleString()} draft FSY IDs prepared. Review origin and badge-name issues before finalizing.`});}catch(error){setMessage({tone:"error",text:error.message||"Unable to prepare FSY IDs."});}finally{setBusy(false);}};
 const finalize=async()=>{setBusy(true);setMessage(null);try{const count=await finalizeFsyIds(sessionId);await reload();await onChanged?.();setConfirmingFinalize(false);setMessage({tone:"success",text:`${Number(count||0).toLocaleString()} IDs finalized. Day-one changes now use the audited replacement workflow.`});}catch(error){setMessage({tone:"error",text:error.message||"Unable to finalize FSY IDs."});}finally{setBusy(false);}};
 const saveBadgeName=async()=>{if(!editing||!badgeName.trim())return;setBusy(true);setMessage(null);try{await updateBadgeName(editing.participantId,badgeName.trim());const name=editing.fullName;setEditing(null);setBadgeName("");await reload();await onChanged?.();setMessage({tone:"success",text:`${name}'s badge name was updated. The registration name was not changed.`});}catch(error){setMessage({tone:"error",text:error.message||"Unable to update badge name."});}finally{setBusy(false);}};
 if(!sessionId)return null;
 return <section className="ops-workspace identity-shell-v5 identity-shell-v28">
  <article className="panel identity-readiness-v5"><div className="identity-readiness-head-v5"><div><span className="kicker">FSY identities</span><h2>{finalized?"Identity set is finalized":"Prepare, review, then finalize"}</h2><p>Only operationally eligible, grouped youth need an FSY ID. People awaiting approval or outside the active cohort are not described as “pending IDs”.</p></div><Status tone={finalized?"good":prepared?"warn":"muted"}>{finalized?"Finalized":prepared?"Draft ready":"Not prepared"}</Status></div><div className="identity-stepper-v5"><div className={prepared?"identity-step-v5 done":"identity-step-v5 current"}><span>1</span><div><b>Prepare IDs</b><small>Create drafts from the active grouped cohort.</small></div></div><div className={prepared&&originClear?"identity-step-v5 done":prepared?"identity-step-v5 current":"identity-step-v5"}><span>2</span><div><b>Review identity</b><small>{counts.preferred} preferred-name review · {counts.reprint} reprint · {readiness?.unresolvedOrigin||0} origin issue</small></div></div><div className={finalized?"identity-step-v5 done":prepared&&originClear?"identity-step-v5 current":"identity-step-v5"}><span>3</span><div><b>Finalize</b><small>Lock the active IDs for normal operations.</small></div></div></div>{canManage?<div className="identity-primary-actions-v5"><button className="secondary" onClick={prepare} disabled={busy||finalized}><ArrowClockwise/>{readiness?.draftIds?"Rebuild draft IDs":"Prepare draft IDs"}</button><button className="primary" onClick={()=>setConfirmingFinalize(true)} disabled={busy||!readiness?.draftIds||!originClear||finalized}><Check/>{finalized?"IDs finalized":"Finalize IDs"}</button></div>:null}</article>
  {message?<MutationFeedback tone={message.tone}>{message.text}</MutationFeedback>:null}
  <div className="ops-metrics identity-metrics-v5"><button onClick={()=>setFilter("ready")} className={filter==="ready"?"active":""}><span>Ready for ID</span><strong>{counts.ready}</strong><small>eligible + grouped, no active ID</small></button><button onClick={()=>setFilter("active")} className={filter==="active"?"active":""}><span>Active IDs</span><strong>{counts.active}</strong><small>{finalized?`${readiness?.finalizedIds||0} finalized`:`${readiness?.draftIds||0} draft`}</small></button><button onClick={()=>setFilter("preferred")} className={`${counts.preferred?"needs-attention ":""}${filter==="preferred"?"active":""}`.trim()}><span>Preferred name review</span><strong>{counts.preferred}</strong><small>Confirm badge display name</small></button><button onClick={()=>setFilter("reprint")} className={`${counts.reprint?"needs-attention ":""}${filter==="reprint"?"active":""}`.trim()}><span>Needs reprint</span><strong>{counts.reprint}</strong><small>Physical badge action</small></button><button onClick={()=>setFilter("origin")} className={`${counts.origin?"needs-attention ":""}${filter==="origin"?"active":""}`.trim()}><span>Origin issues</span><strong>{counts.origin}</strong><small>{counts.origin?"Resolve before finalizing":"Clear"}</small></button></div>
  <article className="panel identity-roster-panel-v5"><div className="identity-roster-head-v5"><div><span className="kicker">Participant identity</span><h2>FSY IDs and badge names</h2><p>Exact IDs rank first; names tolerate order, accents, prefixes and small spelling mistakes.</p></div><IdentificationCard size={24}/></div><div className="identity-controls-v5"><SearchField value={search} onChange={setSearch} label="Search FSY identities" placeholder="FSY ID, name, ward, stake, company or group"/><div className="registration-filter-chips identity-filter-chips-v5 identity-filter-chips-v28" role="group">{FILTERS.map(item=><button type="button" key={item.value} className={filter===item.value?"active":""} onClick={()=>setFilter(item.value)}><span>{item.label}</span><b>{counts[item.value]}</b></button>)}</div></div><div className="identity-result-summary-v5"><b>{filtered.length}</b><span>shown{search?` for “${search}”`:""}</span>{filter!=="all"?<button type="button" className="text-action" onClick={()=>setFilter("all")}>Clear filter</button>:null}</div><div className="identity-roster-v5">{filtered.map(row=><div className={`identity-row-v5${row.nameReviewRequired||row.needsReprint?" review":""}`} key={row.participantId}><div className="identity-person-v5"><span className="person-avatar">{initials(row.fullName)}</span><span><b><PersonName person={{...row,id:row.participantId}}/></b><small>{row.unit||"Unit not recorded"}{row.stake?` · ${row.stake}`:""}</small></span></div><div className="identity-id-v5"><span>FSY ID</span><b className="mono-id">{row.fsyId||"Not issued"}</b><small>{row.fsyId?(row.originCode||"Origin unresolved"):readyForId(row)?"Ready to issue":"Not in active ID cohort"}</small>{row.previousFsyIds?.length?<small>Previous: {row.previousFsyIds.join(", ")}</small>:null}</div><div className="identity-group-v5"><span>Company / group</span><b>{row.companyName||"Unassigned"}</b><small>{row.groupName||"No counselor group"}</small></div><div className="identity-badge-v5"><span>Badge</span><button type="button" className="identity-badge-button-v5" disabled={!canManage||!row.fsyId} onClick={()=>{setEditing(row);setBadgeName(row.badgeName||row.fullName);}}>{row.badgeName||row.fullName}</button>{row.needsReprint?<small className="warning-copy"><WarningCircle/> Reprint needed</small>:row.nameReviewRequired?<small className="warning-copy"><WarningCircle/> Preferred name review</small>:<small>Ready</small>}</div></div>)}{!filtered.length?<Empty icon={IdentificationCard} title="Nothing in this view" text="Clear the filter or try another search."/>:null}</div></article>
  <details className="panel identity-origin-details-v5"><summary><span><b>Origin code registry</b><small>{origins.length} stake, district or mission codes</small></span><span>+</span></summary><div><p className="form-hint">Codes stay explicit so similar place names cannot silently share an identifier.</p><div className="origin-code-grid">{origins.map(origin=><div key={origin.code}><b>{origin.code}</b><span>{origin.name}</span><small>{origin.participantCount} participants{origin.aliases.length?` · aliases: ${origin.aliases.join(", ")}`:""}</small></div>)}</div></div></details>
  <DismissibleLayer open={Boolean(editing)} onClose={()=>{if(!busy){setEditing(null);setBadgeName("");}}} title="Edit badge name" sheet className="identity-badge-modal-v5">{editing?<div className="identity-badge-sheet-v5"><header><span className="kicker">Badge name</span><h2>{editing.fullName}</h2><p>This changes the printed badge name only.</p></header><div className="identity-badge-context-v5"><span><small>FSY ID</small><b className="mono-id">{editing.fsyId}</b></span><span><small>Registered name</small><b>{editing.fullName}</b></span>{meaningfulPreferred(editing)?<span><small>Preferred name</small><b>{editing.preferredName}</b></span>:null}</div><label className="ops-confirm-field"><span>Badge name</span><input autoFocus value={badgeName} onChange={event=>setBadgeName(event.target.value)}/></label><div className="ops-confirm-actions"><button className="secondary" onClick={()=>{setEditing(null);setBadgeName("");}} disabled={busy}>Cancel</button><button className="primary" onClick={saveBadgeName} disabled={busy||!badgeName.trim()}>{busy?"Saving…":"Save badge name"}</button></div></div>:null}</DismissibleLayer>
  <DismissibleLayer open={confirmingFinalize} onClose={()=>!busy&&setConfirmingFinalize(false)} title="Finalize FSY IDs" sheet><div className="ops-confirm-sheet"><header><span className="kicker">Final step</span><h2>Finalize FSY IDs?</h2><p>Day-one changes will then use the audited vacancy and replacement workflow.</p></header><div className="ops-confirm-warning"><b>{readiness?.draftIds||0} draft IDs</b><span>will become final. Registration names remain unchanged.</span></div><div className="ops-confirm-actions"><button className="secondary" onClick={()=>setConfirmingFinalize(false)} disabled={busy}>Cancel</button><button className="primary" onClick={finalize} disabled={busy}>{busy?"Finalizing…":"Confirm finalization"}</button></div></div></DismissibleLayer>
 </section>;
}
