import { useEffect,useMemo,useState } from "react";
import { ArrowRight } from "@phosphor-icons/react/ArrowRight";
import { WarningCircle } from "@phosphor-icons/react/WarningCircle";
import { PersonName } from "../components/PersonPeek.jsx";
import { Empty,MutationFeedback,SearchField,Status } from "../components/UI.jsx";
import { loadStaff } from "../lib/operations.js";
import { searchPeople } from "../lib/person-search.js";
import { staffException,staffState } from "../lib/staff-state.js";

const ROLE_LABELS={counselor:"Counselor",assistant_coordinator:"Assistant coordinator",coordinator:"Coordinator",committee_member:"Committee member",logistics_admin:"Logistical administrator",session_director:"Session directing couple",other:"Other staff"};

function readinessIssue(person){return staffException(person)||"Clear";}
function readinessAction(person){const issue=staffException(person)||"";if(/confirmation/i.test(issue))return"Review confirmation";if(/arrival|expected|no-show|absent/i.test(issue))return"Review arrival & service";if(person.operationalRole==="counselor"&&!person.counselorGroupId)return"Assign counselor group";if(person.operationalRole==="assistant_coordinator"&&!(person.companyIds||[]).length)return"Assign company coverage";return issue?"Review assignment":"Open assignment";}

export function StaffReadinessV31({sessionId,onNavigate}){
 const[staff,setStaff]=useState([]),[query,setQuery]=useState(""),[filter,setFilter]=useState("attention"),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{let active=true;setLoading(true);setError("");loadStaff(sessionId).then(rows=>active&&setStaff(rows)).catch(err=>active&&setError(err.message||"Staff readiness could not load.")).finally(()=>active&&setLoading(false));return()=>{active=false;};},[sessionId]);
 const current=staff.filter(person=>person.isCurrent!==false&&person.registrationStatus!=="cancelled");
 const counts=useMemo(()=>({approved:current.filter(p=>p.registrationStatus==="approved").length,confirmation:current.filter(p=>staffState(p).clearance==="confirmation_required").length,cleared:current.filter(p=>staffState(p).clearance==="cleared").length,cancelled:staff.filter(p=>p.registrationStatus==="cancelled"||p.isCurrent===false).length,attention:current.filter(p=>Boolean(staffException(p))).length}),[staff]);
 const rows=useMemo(()=>searchPeople(current.filter(person=>filter==="all"||filter==="attention"&&Boolean(staffException(person))||filter==="confirmation"&&staffState(person).clearance==="confirmation_required"||filter==="cleared"&&staffState(person).clearance==="cleared"),query).slice(0,160),[current,filter,query]);
 const state=loading?{tone:"muted",label:"Loading",title:"Checking Staff readiness…"}:error?{tone:"danger",label:"Could not load",title:"Staff readiness needs a retry"}:counts.confirmation?{tone:"warn",label:"Confirmation required",title:`${counts.confirmation} Staff need confirmation`}:counts.attention?{tone:"warn",label:"Review needed",title:`${counts.attention} Staff need a review`}:{tone:"good",label:"Ready",title:"Staff readiness is clear"};
 const openStaff=(person)=>onNavigate?.({view:"assignments",tab:"people",filter:readinessIssue(person)==="Clear"?"all":"attention",staffId:person.id,returnTo:{view:"registration",mode:"readiness"}});
 return <section className="staff-readiness-v31" aria-busy={loading}>
  {error?<MutationFeedback tone="error">{error}</MutationFeedback>:null}
  <article className="panel staff-readiness-v31-head"><div><span className="kicker">Staff readiness</span><h2>{state.title}</h2><p>{loading?"Checking source approval, service clearance and operational assignments.":"This view identifies the Staff member and the next place to work. Assignment changes still happen in Assignments."}</p></div><Status tone={state.tone}>{state.label}</Status></article>
  <div className="staff-readiness-v31-summary" aria-label="Staff readiness summary"><button type="button" disabled={loading} onClick={()=>setFilter("attention")} aria-pressed={filter==="attention"}><b>{loading?"…":counts.attention}</b><span>Need review</span></button><button type="button" disabled={loading} onClick={()=>setFilter("confirmation")} aria-pressed={filter==="confirmation"}><b>{loading?"…":counts.confirmation}</b><span>Need confirmation</span></button><button type="button" disabled={loading} onClick={()=>setFilter("cleared")} aria-pressed={filter==="cleared"}><b>{loading?"…":counts.cleared}</b><span>Cleared to plan</span></button><button type="button" disabled={loading} onClick={()=>setFilter("all")} aria-pressed={filter==="all"}><b>{loading?"…":current.length}</b><span>Current Staff</span></button></div>
  <article className="panel staff-readiness-v31-list"><div className="staff-readiness-v31-tools"><SearchField value={query} onChange={setQuery} label="Find Staff" placeholder="Staff name, unit or responsibility" disabled={loading}/><button type="button" className="secondary" disabled={loading} onClick={()=>onNavigate?.({view:"assignments",tab:"people",filter:filter==="confirmation"||filter==="attention"?"attention":"all",returnTo:{view:"registration",mode:"readiness"}})}>Review all in Assignments<ArrowRight/></button></div>{loading?<div className="staff-readiness-loading-v30" role="status" aria-live="polite"><span className="workspace-state state-loading"><i/>Loading Staff readiness</span><small>The current result will appear when the roster check finishes.</small></div>:<div className="staff-readiness-v31-table" role="table" aria-label="Staff readiness"><div className="staff-readiness-v31-columns" role="row"><span>Staff member</span><span>Responsibility</span><span>Readiness</span><span>Next action</span></div>{rows.map(person=><div className="staff-readiness-v31-row" role="row" key={person.id}><div><PersonName person={person} kind="staff"/><small>{person.unit||"Unit not recorded"}</small></div><div><small>Responsibility</small><b>{ROLE_LABELS[person.operationalRole]||"Staff"}</b></div><div><small>Readiness</small><Status tone={staffException(person)?"warn":"good"}>{readinessIssue(person)}</Status></div><div><small>Next action</small><button type="button" className="text-action" onClick={()=>openStaff(person)}>{readinessAction(person)}<ArrowRight/></button></div></div>)}</div>}{!loading&&!rows.length?<Empty icon={WarningCircle} title="No Staff in this view" text="Change the filter or search for another person."/>:null}</article>
 </section>;
}
