import { useState } from 'react';
import { DismissibleLayer,MutationFeedback } from './UI.jsx';
import { supabase } from '../lib/supabase.js';

export function AccountSetup({teams=[],companies=[],onCreate,onClose}) {
 const [name,setName]=useState('');const [email,setEmail]=useState('');const [role,setRole]=useState('committee_viewer');const [teamKeys,setTeamKeys]=useState([]);const [companyIds,setCompanyIds]=useState([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [created,setCreated]=useState(null);const [copied,setCopied]=useState(false);
 const submit=async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await onCreate({displayName:name,email,role,companyIds:role==='assistant_coordinator'?companyIds:[],committeeScope:teamKeys});setCreated(result);}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <DismissibleLayer open onClose={()=>!busy&&onClose()} title="Invite website account" sheet><div className="headcount-create">{created?<><h2>Setup is ready</h2><p>Share this one-time code with {name}. It is valid only for their email address.</p><label>Setup code<input readOnly value={created.code}/></label><p>Expires {new Date(created.expiresAt).toLocaleString()}</p><button className="primary" onClick={async()=>{try{await navigator.clipboard.writeText(`${window.location.origin}/?invite=${encodeURIComponent(created.code)}`);setCopied(true);}catch{setError('Copy failed. Select the code above to copy it.');}}}>{copied?'Copied':'Copy setup link'}</button><button className="secondary" onClick={onClose}>Done</button></>:<form className="account-setup-form" onSubmit={submit}><h2>Invite website account</h2><p>A Staff record is not required. Choose the responsibilities this person needs.</p><label>Name<input required minLength={2} maxLength={80} value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Website role<select value={role} onChange={e=>setRole(e.target.value)}><option value="committee_viewer">Committee member</option><option value="assistant_coordinator">Assistant coordinator</option><option value="coordinator">Coordinator</option><option value="logistics_admin">Logistical administrator</option><option value="session_director">Session directing couple</option></select></label>{role==='assistant_coordinator'?<fieldset><legend>Assigned companies</legend><p>For existing Staff, use their linked account so assignment changes sync automatically.</p>{companies.map(c=><label className="account-choice" key={c.id}><input type="checkbox" checked={companyIds.includes(c.id)} onChange={e=>setCompanyIds(ids=>e.target.checked?[...ids,c.id]:ids.filter(id=>id!==c.id))}/>{c.name}</label>)}</fieldset>:null}<TeamChoices teams={teams} selected={teamKeys} onChange={setTeamKeys}/><div className="field-sheet-actions"><button type="button" className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!onCreate||(role==='committee_viewer'&&!teamKeys.length)||(role==='assistant_coordinator'&&!companyIds.length)}>{busy?'Preparing…':'Create setup code'}</button></div></form>}{error?<MutationFeedback tone="error">{error}</MutationFeedback>:null}</div></DismissibleLayer>;
}
export function TeamChoices({teams,selected,onChange}) {return <fieldset><legend>Additional committee responsibilities</legend>{teams.map(t=><label className="account-choice" key={t.key}><input type="checkbox" checked={selected.includes(t.key)} onChange={e=>onChange(e.target.checked?[...selected,t.key]:selected.filter(k=>k!==t.key))}/><span><b>{t.name}</b><small>{t.description}</small></span></label>)}</fieldset>;}
export function AccountTeams({user,sessionId,teams,onClose,onSaved}) {
 const [selected,setSelected]=useState(user.teamKeys||[]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 return <DismissibleLayer open onClose={()=>!busy&&onClose()} title="Committee responsibilities" sheet><div className="headcount-create"><h2>{user.name}</h2><p>These tools are added to their role and company responsibilities.</p><TeamChoices teams={teams} selected={selected} onChange={setSelected}/>{error?<MutationFeedback tone="error">{error}</MutationFeedback>:null}<div><button className="secondary" onClick={onClose} disabled={busy}>Cancel</button><button className="primary" disabled={busy} onClick={async()=>{setBusy(true);try{const {error:e}=await supabase.rpc('set_account_teams',{p_session_id:sessionId,p_user_id:user.userId,p_team_keys:selected});if(e)throw e;await onSaved?.();onClose();}catch(e){setError(e.message);}finally{setBusy(false);}}}>Save responsibilities</button></div></div></DismissibleLayer>;
}
