import {useMemo,useState} from 'react';
import {DismissibleLayer,SearchField} from './UI.jsx';
import {searchPeople} from '../lib/person-search.js';
import {addOnSiteStaff,loadOnSiteReferenceDate} from '../lib/onsite.js';
import {ageOnDate,validateManualStaff} from '../lib/registration.js';
import './operational-state.css';
export function OnSiteStaffSheet({staff,sessionId,onClose,onSaved}){
 const [query,setQuery]=useState(''),[reviewed,setReviewed]=useState(false),[form,setForm]=useState({firstName:'',lastName:'',preferredName:'',sex:'',birthday:'',unit:'',stake:'',phone:'',email:'',operationalRole:'counselor'}),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const matches=useMemo(()=>query.trim()?searchPeople(staff,query).slice(0,12):[],[staff,query]);
 const save=async e=>{e.preventDefault();setBusy(true);setError('');try{const date=await loadOnSiteReferenceDate(sessionId);const errors=validateManualStaff({...form,age:ageOnDate(form.birthday,date)},reviewed);if(errors.length)throw Error(errors.join(' '));const id=await addOnSiteStaff({sessionId,...form});await onSaved(id);onClose();}catch(e){setError(e.message||'Could not add staff');}finally{setBusy(false);}};
 return <DismissibleLayer open onClose={()=>!busy&&onClose()} title="Add on-site Staff" sheet className="operations-state-layer"><form className="operations-state-form" onSubmit={save}><header><h2>Add on-site Staff</h2><button type="button" className="icon-button" disabled={busy} onClick={onClose} aria-label="Close">×</button></header><SearchField value={query} onChange={value=>{setQuery(value);setReviewed(false);}} label="Search existing Staff first" placeholder="Full or preferred name"/>{matches.map(p=><div key={p.id}><b>{p.name}</b><small> · {p.unit} · {p.registrationStatus}</small></div>)}{query.trim().length>=3?<label className="check-row"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I checked these results and this is a different person.</label>:null}{reviewed?<>{[['firstName','First name','text'],['lastName','Last name','text'],['birthday','Date of birth','date'],['unit','Ward / branch','text'],['stake','Stake / district','text'],['phone','Phone','tel'],['email','Email','email']].map(([key,label,type])=><label key={key}>{label}<input type={type} required={['firstName','lastName','birthday','unit'].includes(key)} maxLength={150} value={form[key]} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}<label>Sex<select required value={form.sex} onChange={e=>setForm({...form,sex:e.target.value})}><option value="">Choose</option><option>Female</option><option>Male</option></select></label><label>Operational role<select value={form.operationalRole} onChange={e=>setForm({...form,operationalRole:e.target.value})}>{[['counselor','Counselor'],['assistant_coordinator','Assistant Coordinator'],['committee_member','Committee member'],['other','Other Staff']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><p>Saved as provisional and needing confirmation. Add committee duties and arrival next. Website Access is optional and separate.</p>{error?<p role="alert">{error}</p>:null}<button className="primary" disabled={busy}>{busy?'Adding…':'Add Staff for confirmation'}</button></>:null}</form></DismissibleLayer>;
}
