import { useState } from "react";
import { recordParticipantException } from "../lib/operational-state.js";
import { recoverableWriteError,useSingleFlight } from "../lib/reliable-action.js";

export function ParticipantExceptionForm({person,onSaved}){
 const runSingleFlight=useSingleFlight();
 const[form,setForm]=useState({allow:true,authority:"",reason:"",registration:false,guardian:false,leadership:false}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false);
 const ready=Boolean(form.authority.trim().length>=3&&form.reason.trim().length>=5&&(!form.allow||(form.registration&&form.guardian&&form.leadership)));
 const change=(next)=>{setSaved(false);setError("");setForm(next);};
 const submit=async(event)=>{event.preventDefault();if(!ready)return;return runSingleFlight(`participant-exception-${person.id}`,async()=>{setBusy(true);setError("");setSaved(false);try{await recordParticipantException(person.id,form);await onSaved?.();setSaved(true);}catch(err){setError(recoverableWriteError(err,"The leadership decision could not be recorded."));}finally{setBusy(false);}});};
 return <details className="participant-exception"><summary>Leadership exception / on-site confirmation</summary><form className="operations-state-form" onSubmit={submit} aria-busy={busy}><p>Record an authorized decision using this existing identity. The source registration and finalized FSY ID stay intact. Continue in Registration for placement and check-in.</p><label>Decision<select disabled={busy} value={form.allow?"allow":"exclude"} onChange={event=>change({...form,allow:event.target.value==="allow"})}><option value="allow">Allow explicit participation exception</option><option value="exclude">Exclude from active youth operations</option></select></label><label>Confirming authority<input required disabled={busy} minLength={3} maxLength={150} value={form.authority} onChange={event=>change({...form,authority:event.target.value})}/></label><label>Reason<textarea required disabled={busy} minLength={5} maxLength={500} value={form.reason} onChange={event=>change({...form,reason:event.target.value})}/></label>{form.allow?[["registration","Required registration forms and terms completed"],["guardian","Guardian consent and contact requirements confirmed (or confirmed not applicable)"],["leadership","Bishop / branch president approval and required FSY leadership permission confirmed"]].map(([key,label])=><label className="check-row" key={key}><input type="checkbox" required disabled={busy} checked={form[key]} onChange={event=>change({...form,[key]:event.target.checked})}/>{label}</label>):null}{error?<p role="alert" aria-live="assertive">{error}</p>:null}{saved?<p role="status" aria-live="polite">Decision recorded. Continue in Registration.</p>:null}<button className="primary" disabled={busy||!ready}>{busy?"Recording…":"Record leadership decision"}</button></form></details>;
}
