import { useState } from 'react';
import { DismissibleLayer, MutationFeedback } from './UI.jsx';
import { staffState, STAFF_PLANNING, STAFF_ARRIVAL, STAFF_CLEARANCE } from '../lib/staff-state.js';
import { setStaffOperationalStatus, updateStaffOperations } from '../lib/operational-state.js';
import './operational-state.css';
const labels={primary:'Primary',reserve:'Reserve',provisional:'Provisional',excluded:'Excluded',expected:'Expected',arrived:'Arrived',no_show:'No-show',left:'Left',cleared:'Cleared',confirmation_required:'Needs confirmation',not_cleared:'Not cleared'};
export function StaffOperationsSheet({person,currentRole,onClose,onSaved,assignment}){
 const initial=staffState(person),director=currentRole==='session_director',leadership=['coordinator','logistics_admin','session_director'].includes(currentRole);
 const initialLifecycle=person.isCurrent===false?'withdrawn':['no_show','left'].includes(initial.arrival)?initial.arrival:'active';
 const [form,setForm]=useState({...initial,authority:'',reason:'',duties:(person.committeeDuties||[]).join(', ')}),[lifecycle,setLifecycle]=useState(initialLifecycle),[lifecycleAuthority,setLifecycleAuthority]=useState(''),[lifecycleReason,setLifecycleReason]=useState(''),[busy,setBusy]=useState(false),[lifecycleBusy,setLifecycleBusy]=useState(false),[error,setError]=useState('');
 const save=async event=>{event.preventDefault();setBusy(true);setError('');try{await updateStaffOperations(person,{...form,duties:form.duties.split(',').map(s=>s.trim()).filter(Boolean)});await onSaved();onClose();}catch(e){setError(e.message||'Could not save staff state');}finally{setBusy(false);}};
 const saveLifecycle=async()=>{if(lifecycle!=='active'&&lifecycleReason.trim().length<5){setError('Add an operational reason before changing this staff member’s active status.');return;}if(lifecycle==='withdrawn'&&lifecycleAuthority.trim().length<3){setError('Add the authorized confirming authority before withdrawing this staff member.');return;}setLifecycleBusy(true);setError('');try{await setStaffOperationalStatus(person,lifecycle,lifecycleAuthority.trim(),lifecycleReason.trim());await onSaved();onClose();}catch(e){setError(e.message||'Could not update this staff member’s operational status. Refresh and review coverage.');}finally{setLifecycleBusy(false);}};
 return <DismissibleLayer open onClose={()=>!busy&&!lifecycleBusy&&onClose()} title={`Staff arrival: ${person.name}`} sheet className="operations-state-layer"><form className="operations-state-form" onSubmit={save}><header><div><span className="kicker">Staff arrival & service</span><h2>{person.name}</h2></div><button type="button" className="icon-button" onClick={onClose} disabled={busy||lifecycleBusy} aria-label="Close">×</button></header><p>{assignment||'Reserve pool · no current responsibility'}</p><p>Source registration: <b>{person.registrationStatus==='awaiting'?'Awaiting approval':person.registrationStatus}</b></p>{error?<MutationFeedback tone="error">{error}</MutationFeedback>:null}
 {[["planning","Planning",STAFF_PLANNING],["arrival","Arrival",STAFF_ARRIVAL],["clearance","Service clearance",STAFF_CLEARANCE]].map(([key,label,values])=><label key={key}>{label}<select value={form[key]} disabled={busy||(key==='clearance'&&!director)} onChange={e=>setForm({...form,[key]:e.target.value})}>{values.map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></label>)}
 {form.clearance!=='cleared'?<p className="notice">Arrival records physical presence. This person needs confirmation before active service.</p>:null}{!director?<p className="form-hint">Only Session Directing Couples record service confirmation.</p>:null}
 <label>Committee duties <small>Separate duties with commas</small><input value={form.duties} maxLength={500} placeholder="Food, Games Night" onChange={e=>setForm({...form,duties:e.target.value})}/></label>
 {form.clearance!==initial.clearance?<label>Confirming authority<input required minLength={3} maxLength={150} value={form.authority} onChange={e=>setForm({...form,authority:e.target.value})}/></label>:null}
 <label>Reason <textarea required={form.clearance!==initial.clearance||['no_show','left'].includes(form.arrival)} minLength={5} maxLength={500} placeholder="Operational reason only; do not record private health details" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})}/></label>
 <details className="staff-operational-lifecycle"><summary>Clear assignments or record a session status</summary><div><p>Use this when someone will not cover their active responsibility. Existing source registration and audit history stay intact; any replacement still needs to be assigned separately.</p><label>Operational status<select value={lifecycle} disabled={lifecycleBusy} onChange={e=>{setLifecycle(e.target.value);setError('');}}><option value="active">Active in operations</option><option value="no_show">No-show</option><option value="left">Left the session</option>{leadership?<option value="withdrawn">Withdrawn from session</option>:null}</select></label>{lifecycle!=='active'?<label>Operational reason<textarea required minLength={5} maxLength={240} value={lifecycleReason} onChange={e=>{setLifecycleReason(e.target.value);setError('');}} placeholder="Why coverage must be cleared"/></label>:null}{lifecycle==='withdrawn'?<label>Authorized authority<input required minLength={3} maxLength={150} value={lifecycleAuthority} onChange={e=>{setLifecycleAuthority(e.target.value);setError('');}} placeholder="Confirming leader or role"/></label>:null}<button type="button" className="secondary danger-text" disabled={lifecycleBusy||busy||!leadership&&lifecycle==='withdrawn'} onClick={saveLifecycle}>{lifecycleBusy?'Saving…':lifecycle==='active'?'Restore active operations':'Clear assignments & record status'}</button></div></details>
 <button className="primary" disabled={busy}>{busy?'Saving…':'Save staff state'}</button></form></DismissibleLayer>;
}
