from pathlib import Path
root=Path(__file__).resolve().parents[1]
def edit(path, fn):
 p=root/path; old=p.read_text(encoding='utf-8'); new=fn(old); p.write_text(new,encoding='utf-8')
edit('src/lib/registration-search-v6.js',lambda s: '''import { personSearchRank, matchesPersonSearch } from './person-search.js';
export const registrationSearchRank = (row,query,housing) => personSearchRank(row,query,[housing?.roomName]);
export const matchesRegistrationSearchV6 = (row,query,housing) => matchesPersonSearch(row,query,[housing?.roomName]);
''')
edit('src/lib/registration-lookup.js',lambda s: 'import { matchesPersonSearch } from "./person-search.js";\n'+s[:s.index('export function matchesRegistrationSearch')]+'''export function matchesRegistrationSearch(row, query, housing) {
 return matchesPersonSearch(row,query,[housing?.roomName]);
}
''')
edit('src/pages/AssignmentsV3.jsx',lambda s: 'import { buildStaffingPlan as buildSuggestions } from "../lib/staffing-planner.js";\nimport { canPlanStaff, staffException } from "../lib/staff-state.js";\nimport { searchPeople, matchesPersonSearch } from "../lib/person-search.js";\n'+s[:s.index('function buildSuggestions(')]+s[s.index('function AssignmentPicker('):])
edit('src/pages/AssignmentsV3.jsx',lambda s:s.replace('staff.filter((person) => person.registrationStatus === "approved" && person.isCurrent !== false)','staff.filter(canPlanStaff)').replace('staff.filter((person) => (roleFilter === "all" || person.operationalRole === roleFilter)\n      && (!text || `${person.name} ${person.unit || ""} ${person.stake || ""} ${ROLE_LABELS[person.operationalRole] || ""}`.toLowerCase().includes(text)))','searchPeople(staff.filter((person) => roleFilter === "all" || person.operationalRole === roleFilter),text)').replace('!text || `${person.name} ${person.unit || ""} ${person.stake || ""}`.toLowerCase().includes(text)','matchesPersonSearch(person,text)').replace('!text || `${groupLabel(group)} ${companyLabel(companyById.get(group.companyId))} ${staffById.get(group.counselorId)?.name || ""}`.toLowerCase().includes(text)','matchesPersonSearch({name:groupLabel(group)},text,[companyLabel(companyById.get(group.companyId)),staffById.get(group.counselorId)?.name])').replace('!text || `${companyLabel(company)} ${(company.assistantCoordinatorIds || []).map((id) => staffById.get(id)?.name || "").join(" ")}`.toLowerCase().includes(text)','matchesPersonSearch({name:companyLabel(company)},text,(company.assistantCoordinatorIds || []).map(id=>staffById.get(id)?.name))').replace('suggestionRows.slice(0, 12).map','suggestionRows.map').replace('<div className="assignment-v2-suggestion-actions">','{suggestions.exceptions?.map(item=><p className="notice" key={item.targetId}>{item.message}</p>)}<div className="assignment-v2-suggestion-actions">'))
edit('src/pages/GroupsV2.jsx',lambda s: 'import { buildStaffingPlan } from "../lib/staffing-planner.js";\nimport { matchesPersonSearch, personSearchRank } from "../lib/person-search.js";\n'+s[:s.index('function shuffled(')]+s[s.index('function LiveGroup('):])
edit('src/pages/GroupsV2.jsx',lambda s:s.replace('makeStaffSuggestions(groups,companies,staff)','buildStaffingPlan(staff,groups,companies,Number(settings.companiesPerAssistantCoordinator||4))').replace('Shuffle suggestions','Regenerate plan').replace('].slice(0,12).map(text=>','].map(text=>'))
edit('src/lib/headcount-roster.js',lambda s: 'import { searchPeople } from "./person-search.js";\n'+s[:s.index('export function searchHeadcount')]+'''export function searchHeadcount(people,query,filter='all') {
 return searchPeople(people.filter(p=>filter==='all'||p.status===filter),query);
}
''')
edit('src/pages/HeadcountRoster.jsx',lambda s: 'import { matchesPersonSearch, personSearchRank } from "../lib/person-search.js";\n'+s.replace("function includesText(person,text){if(!text)return true;return [person.display_name,person.fsy_id,person.company_name,person.group_name,person.person_type].filter(Boolean).join(' ').toLowerCase().includes(text);}","function includesText(person,text){return matchesPersonSearch(person,text);}").replace(".sort((a,b)=>(STATUS_ORDER[a.status]??9)",".sort((a,b)=>personSearchRank(a,text)-personSearchRank(b,text)||(STATUS_ORDER[a.status]??9)"))
edit('src/pages/PeopleV2.jsx',lambda s: 'import { searchPeople } from "../lib/person-search.js";\n'+s[:s.index(' const rows=useMemo(')]+''' const rows=useMemo(()=>{if(!query.trim())return [];const source=(tab==="staff"?staff:participants).filter(person=>tab!=="staff"||roleFilter==="all"||person.operationalRole===roleFilter);return searchPeople(source,query,person=>{const group=groupMap.get(person.groupId||person.counselorGroupId);return [group?.displayName,companyMap.get(group?.companyId)?.displayName,...(person.companyIds||[]).map(id=>companyMap.get(id)?.displayName)];}).slice(0,80);},[participants,staff,tab,query,roleFilter,groupMap,companyMap]);
'''+s[s.index(' const openPerson='):])
edit('src/pages/HousingV6.jsx',lambda s:'import { matchesPersonSearch } from "../lib/person-search.js";\n'+s.replace('!text || `${person.name} ${person.context} ${person.group || ""} ${person.company || ""}`.toLowerCase().includes(text)','matchesPersonSearch(person,text,[person.context])'))
edit('src/pages/FoodV3.jsx',lambda s:'import { matchesPersonSearch } from "../lib/person-search.js";\n'+s.replace('!text || `${person.name} ${person.fsyId} ${person.company} ${person.group}`.toLowerCase().includes(text)','matchesPersonSearch(person,text)').replace('!text||`${item.name} ${item.dietaryInformation} ${item.group} ${item.company}`.toLowerCase().includes(text)','matchesPersonSearch(item,text,[item.dietaryInformation])'))
edit('src/pages/Birthdays.jsx',lambda s:'import { matchesPersonSearch } from "../lib/person-search.js";\n'+s.replace('!text || searchText(person).includes(text)','matchesPersonSearch(person,text)'))
