from pathlib import Path
root=Path(__file__).resolve().parents[1]
def edit(path,fn):
 p=root/path;s=p.read_text(encoding='utf-8');p.write_text(fn(s),encoding='utf-8')
def names(s):return 'import { PersonName } from "../components/PersonPeek.jsx";\n'+s
edit('src/App.jsx',lambda s:'import { PersonProvider } from "./components/PersonPeek.jsx";\n'+s.replace('>{content}</AppShell>','><PersonProvider participants={ownParticipants} assignment={assignment} sessionId={sessionInfo?.id} onNavigate={navigate} view={effectiveActive}>{content}</PersonProvider></AppShell>').replace('<Assignments sessionId=', '<Assignments currentRole={currentRole} sessionId=').replace('<People companyIds=', '<People currentRole={currentRole} onRefresh={refreshOperationalIdentity} companyIds='))
edit('src/components/person-peek.css',lambda s:s.replace('.person-peek-layer .dismissible-panel','.layer-panel.person-peek-layer'))
edit('src/pages/AssignmentsV3.jsx',lambda s:names(s).replace('<div className="assignments-v3-person"><span className="person-avatar">{personInitials(person.name)}</span><span><b>{person.name}</b>','<div className="assignments-v3-person"><span className="person-avatar">{personInitials(person.name)}</span><span><PersonName person={person} kind="staff"/>').replace('<b>{counselor.name}</b>','<PersonName person={counselor} kind="staff"/>').replace('<b>{assistant.name}</b>','<PersonName person={assistant} kind="staff"/>'))
edit('src/pages/GroupsV2.jsx',lambda s:names(s).replace('<b>{person.fullName}</b>','<PersonName person={person} context={{label:"Counselor group",value:groupName(group)}}/>').replace('{open?<div className="groups-v2-members">','{open?<div className="groups-v2-members">{counselor?<div><PersonName person={counselor} kind="staff" context={{label:"Supervises",value:groupName(group)}}/></div>:null}').replace('{open?<div className="groups-v2-company-body">','{open?<div className="groups-v2-company-body">{assistants.map(person=><PersonName key={person.id} person={person} kind="staff" context={{label:"Company responsibility",value:companyName(company)}}/>)}'))
edit('src/pages/HeadcountRoster.jsx',lambda s:names(s).replace('<b>{p.display_name}</b>','<PersonName person={{...p,id:p.person_id}} kind={p.person_type} context={{label:"Head count",value:STATUS_LABEL[p.status]||p.status}}/>'))
edit('src/pages/Birthdays.jsx',lambda s:names(s).replace('<h3>{person.name}</h3>','<h3><PersonName person={person} kind={staff?"staff":"participant"} context={{label:"Birthday",value:person.date||person.birthday||"Celebrating during FSY"}}/></h3>'))
edit('src/pages/FoodV3.jsx',lambda s:names(s).replace('<b>{person.name}</b>','<PersonName person={person} context={{label:selectedService.label,value:served?"Served":"Not served"}}/>'))
edit('src/pages/RegistrationJourneyV5.jsx',lambda s:names(s).replace('<button type="button" className="regjourney-person-button" onClick={() => openPerson(row)}>','<div className="regjourney-person-button">').replace('<b>{row.fullName}</b>','<PersonName person={{...row,id:row.participantId}} context={{label:"Registration",value:problem||arrivalLabel(row)}}/>').replace('</span>\n            </button>\n            <div className="regjourney-assignment">','</span>\n            </div>\n            <div className="regjourney-assignment">'))
edit('src/pages/HousingV6.jsx',lambda s:names(s).replace('return <button type="button" key={`${person.kind}:${person.id}`} className={person.queue && index === 0 ? "priority" : ""} disabled={!canManage} onClick={() => canManage && setSelected({ person, assignment })}>','return <div key={`${person.kind}:${person.id}`} className={`housing-person-identity-row ${person.queue && index === 0 ? "priority" : ""}`}>').replace('<span className="copy"><b>{person.name}</b>','<span className="copy"><PersonName person={person} kind={person.kind} context={{label:"Housing",value:assignment?.roomName||"Room not assigned"}}/>').replace('<span className="assignment">{assignment ?', '<button type="button" className="assignment person-name" disabled={!canManage} onClick={()=>setSelected({person,assignment})}>{assignment ?').replace('</span>\n            </button>;','</button>\n            </div>;'))
edit('src/pages/Reports.jsx',lambda s:names(s).replace('import { useEffect','import { matchesPersonSearch, personSearchRank } from "../lib/person-search.js";\nimport { useEffect').replace('return columns.some(([key, , type]) => formatReportValue(row[key], type).toLowerCase().includes(text));','return matchesPersonSearch(row,text,columns.map(([key,,type])=>formatReportValue(row[key],type)));').replace('rows.filter((row) => rowMatches(row, selected.columns, query))','rows.filter((row) => rowMatches(row, selected.columns, query)).sort((a,b)=>personSearchRank(a,query)-personSearchRank(b,query))').replace('{formatReportValue(row[key], type)}</td>','{key==="full_name"&&(row.participant_id||row.staff_id||row.person_id)?<PersonName person={{...row,id:row.participant_id||row.staff_id||row.person_id}} kind={row.staff_id?"staff":"participant"}/>:formatReportValue(row[key], type)}</td>'))
edit('src/lib/registration.js',lambda s:s.replace('  if (person.isCurrent === false)', '''  if (person.serverEligibility && typeof person.serverEligibility.eligible === "boolean") return {ok:person.serverEligibility.eligible,reason:person.serverEligibility.reason||"Needs review"};
  if (person.isCurrent === false)''',1))
