from pathlib import Path
root=Path(__file__).resolve().parents[1]
def edit(path,fn):
 p=root/path;s=p.read_text(encoding='utf-8');p.write_text(fn(s),encoding='utf-8')
edit('src/lib/operations.js',lambda s:s.replace('{ data: companyAssignments, error: assignmentError }]','{ data: companyAssignments, error: assignmentError }, {data: operationRows,error:operationsError}, {data:dutyRows,error:dutiesError}]').replace('client().from("staff_company_assignments").select("staff_id, company_id").eq("session_id", sessionId),\n  ]);','client().from("staff_company_assignments").select("staff_id, company_id").eq("session_id", sessionId),\n    client().from("staff_operations").select("staff_id,planning_state,arrival_state,service_clearance,revision"),\n    client().from("staff_committee_duties").select("staff_id,duty"),\n  ]);',1).replace('  const counselorGroup =','  if(operationsError) throw operationsError;\n  if(dutiesError) throw dutiesError;\n  const operationMap=new Map((operationRows||[]).map(row=>[row.staff_id,row]));\n  const counselorGroup =',1).replace('    sourceRole: row.staff_role,','    sourceRole: row.staff_role,\n    planningState:operationMap.get(row.id)?.planning_state,\n    arrivalState:operationMap.get(row.id)?.arrival_state,\n    serviceClearance:operationMap.get(row.id)?.service_clearance,\n    operationsRevision:operationMap.get(row.id)?.revision,\n    committeeDuties:(dutyRows||[]).filter(d=>d.staff_id===row.id).map(d=>d.duty),',1))
edit('src/lib/operations.js',lambda s:s[:s.index('export async function applyStaffAssignmentPlan')]+'''export async function applyStaffAssignmentPlan(sessionId, suggestions) {
 const {data,error}=await client().rpc("apply_staff_plan_v26",{p_session_id:sessionId,p_plan:suggestions});
 if(error)throw error;
 if(Number(data?.counselor_assignments)!==(suggestions.counselors||[]).length||Number(data?.assistant_coordinator_assignments)!==(suggestions.assistants||[]).length)throw new Error("Applied plan count differs; refresh coverage before continuing.");
 return data;
}

'''+s[s.index('export async function',s.index('export async function applyStaffAssignmentPlan')+25):])
edit('src/pages/AssignmentsV3.jsx',lambda s:'import { StaffOperationsSheet } from "../components/StaffOperationsSheet.jsx";\nimport { saveStaffCompanyLimit } from "../lib/operational-state.js";\n'+s.replace('export function Assignments({ sessionId','export function Assignments({ currentRole, sessionId').replace('  const [staff, setStaff]', '  const [operationsPerson,setOperationsPerson]=useState(null);\n  const [planningLimit,setPlanningLimit]=useState(4);\n  const [staffFilter,setStaffFilter]=useState("all");\n  const [staff, setStaff]').replace('    setSettings(nextSettings);','    setSettings(nextSettings);setPlanningLimit(nextSettings.companiesPerAssistantCoordinator);').replace('const openGroups = groups.filter((group) => !group.counselorId);','const openGroups = groups.filter((group) => !group.counselorId || !canPlanStaff(staffById.get(group.counselorId)||{isCurrent:false}));').replace('const openCompanies = companies.filter((company) => !company.assistantCoordinatorIds?.length);','const openCompanies = companies.filter((company) => !(company.assistantCoordinatorIds||[]).some(id=>canPlanStaff(staffById.get(id)||{isCurrent:false})));').replace('roleFilter === "all" || person.operationalRole === roleFilter),text)','(roleFilter === "all" || person.operationalRole === roleFilter)&&(staffFilter==="all"||staffFilter==="attention"&&Boolean(staffException(person))||staffFilter==="reserve"&&person.planningState==="reserve"||staffFilter===person.arrivalState)),text)').replace('[staff, query, roleFilter]','[staff, query, roleFilter,staffFilter]').replace('<div className="assignments-v3-context"><small>Assignment</small><b>{personContext(person)}</b></div>','<div className="assignments-v3-context"><small>Assignment</small><b>{personContext(person)}</b>{staffException(person)?<small className="danger-text">{staffException(person)}</small>:null}{person.committeeDuties?.length?<small>{person.committeeDuties.join(" · ")}</small>:null}{canManage?<button type="button" className="text-action" onClick={()=>setOperationsPerson(person)}>Arrival & service</button>:null}</div>').replace('<div className="assignments-v3-nav">','''<details><summary>Staffing planning limit</summary><div className="staff-planning-controls"><label>Maximum companies per Assistant Coordinator<input type="number" min="1" max="20" value={planningLimit} onChange={e=>setPlanningLimit(Number(e.target.value))}/></label><span>{assistants.length} available ACs × {planningLimit} = {assistants.length*planningLimit} company places for {companies.length} companies.</span><button className="secondary" disabled={!canManage||Boolean(busy)} onClick={async()=>{setBusy("limit");try{await saveStaffCompanyLimit(sessionId,planningLimit);await refresh();setSuggestions(null);}catch(e){setError(e.message);}finally{setBusy("");}}}>Save planning limit</button></div></details>
    <div className="assignments-v3-nav">''').replace('<SearchField value={query} onChange={setQuery} label="Search staff" placeholder="Name, unit or responsibility" />','''<SearchField value={query} onChange={setQuery} label="Search staff" placeholder="Name, unit or responsibility" /><label>Staff state<select value={staffFilter} onChange={e=>setStaffFilter(e.target.value)}>{[["all","All staff"],["attention","Needs attention"],["reserve","Reserve pool"],["expected","Expected"],["arrived","Arrived"],["no_show","No-show"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>''').replace('    {setupTarget ?','    {operationsPerson?<StaffOperationsSheet person={operationsPerson} currentRole={currentRole} assignment={personContext(operationsPerson)} onClose={()=>setOperationsPerson(null)} onSaved={async()=>{await refresh();setSuggestions(null);setNotice("Staff state saved.");}}/>:null}\n    {setupTarget ?'))
edit('src/pages/PeopleV2.jsx',lambda s:'import { ParticipantExceptionForm } from "../components/ParticipantExceptionForm.jsx";\nimport { personIdentity } from "../lib/person-identity.js";\nimport "../components/operational-state.css";\n'+s.replace('function PersonSheet({selected,','function PersonSheet({currentRole,onRefresh,selected,').replace('export function People({companyIds','export function People({currentRole,onRefresh,companyIds').replace('<PersonSheet selected=','<PersonSheet currentRole={currentRole} onRefresh={onRefresh} selected=').replace(' </div></DismissibleLayer>;',' {participant&&currentRole==="session_director"?<ParticipantExceptionForm person={person} onSaved={onRefresh}/>:null}</div></DismissibleLayer>;',1).replace('<div><span>Operational status</span><b>{eligibility?.reason||"Ready"}</b></div>','{!eligibility?.ok?<div><span>Needs attention</span><b>{eligibility?.reason}</b></div>:null}<div><span>Age at session</span><b>{person.age??"Not recorded"}</b></div>'))
