-- FSY Kumasi operations v2: identity, arrival reconciliation, and leadership permissions.
-- Designed to preserve source registration identity while adding stable operational IDs.

alter table public.companies add column if not exists operational_number integer;
update public.companies
set operational_number = nullif(regexp_replace(name, '\D', '', 'g'), '')::integer
where operational_number is null and name ~ '\d';

alter table public.counselor_groups add column if not exists operational_number integer;
update public.counselor_groups
set operational_number = nullif(regexp_replace(name, '\D', '', 'g'), '')::integer
where operational_number is null and name ~ '\d';

create table if not exists public.origin_code_registry (
  id uuid primary key default extensions.gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  canonical_name text not null,
  code text not null,
  aliases text[] not null default '{}',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(session_id, canonical_name),
  unique(session_id, code)
);

create table if not exists public.participant_badge_assignments (
  id uuid primary key default extensions.gen_random_uuid(),
  session_id uuid not null references public.sessions(id) on delete cascade,
  participant_id uuid not null references public.participants(id) on delete cascade,
  company_id uuid not null references public.companies(id),
  group_id uuid not null references public.counselor_groups(id),
  slot_number integer not null check (slot_number between 1 and 99),
  origin_code text not null,
  fsy_id text not null,
  badge_name text not null,
  state text not null default 'draft' check (state in ('draft','finalized','retired')),
  needs_reprint boolean not null default false,
  replacement_for uuid references public.participant_badge_assignments(id),
  assigned_by uuid,
  assigned_at timestamptz not null default now(),
  finalized_by uuid,
  finalized_at timestamptz,
  retired_by uuid,
  retired_at timestamptz,
  note text
);

create unique index if not exists participant_badge_active_participant_uq
  on public.participant_badge_assignments(session_id, participant_id)
  where state <> 'retired';
create unique index if not exists participant_badge_active_slot_uq
  on public.participant_badge_assignments(session_id, company_id, slot_number)
  where state <> 'retired';
create unique index if not exists participant_badge_active_fsy_id_uq
  on public.participant_badge_assignments(session_id, fsy_id)
  where state <> 'retired';
create index if not exists participant_badge_session_company_idx
  on public.participant_badge_assignments(session_id, company_id, slot_number);

create table if not exists public.participant_arrival_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.sessions(id) on delete cascade,
  participant_id uuid not null references public.participants(id) on delete cascade,
  status text not null check (status in ('expected','expected_later','unknown','confirmed_not_attending','replaced')),
  note text,
  recorded_by uuid,
  recorded_at timestamptz not null default now()
);
create index if not exists participant_arrival_events_session_participant_idx
  on public.participant_arrival_events(session_id, participant_id, recorded_at desc);

alter table public.origin_code_registry enable row level security;
alter table public.participant_badge_assignments enable row level security;
alter table public.participant_arrival_events enable row level security;
revoke all on public.origin_code_registry from anon, authenticated;
revoke all on public.participant_badge_assignments from anon, authenticated;
revoke all on public.participant_arrival_events from anon, authenticated;

-- Canonical origin registry. Keep Hagan's requested codes, and resolve the Tamale/Techiman collision explicitly.
insert into public.origin_code_registry(session_id, canonical_name, code, aliases)
select s.id, seed.canonical_name, seed.code, seed.aliases
from public.sessions s
cross join (values
  ('Kumasi Ghana University Stake','KGUS','{}'::text[]),
  ('Kumasi Ghana Suame Stake','KGSS','{}'::text[]),
  ('Kumasi Ghana Bantama Stake','KGBS',array['Bantama Stake']::text[]),
  ('Tamale Ghana District','TGD','{}'::text[]),
  ('Obuasi Ghana District','OGD','{}'::text[]),
  ('Ghana Kumasi Mission','GKM','{}'::text[]),
  ('Ejisu Ghana Stake','EGS','{}'::text[]),
  ('Techiman Ghana District','TEGD','{}'::text[]),
  ('Bibiani Ghana District','BGD','{}'::text[]),
  ('Kumasi Ghana Konongo Stake','KGKS','{}'::text[]),
  ('Kumasi Ghana Dichemso Stake','KGDS','{}'::text[]),
  ('Sunyani Ghana District','SGD','{}'::text[])
) as seed(canonical_name,code,aliases)
where s.year = 2026 and lower(s.name) like '%kumasi%'
on conflict(session_id, canonical_name) do update
set code=excluded.code, aliases=excluded.aliases, active=true, updated_at=now();

create or replace function private.origin_code_for_participant(p_participant public.participants)
returns text
language sql
stable
security definer
set search_path=''
as $$
  select o.code
  from public.origin_code_registry o
  where o.session_id=p_participant.session_id
    and o.active
    and (
      lower(trim(o.canonical_name))=lower(trim(coalesce(p_participant.stake_name,'')))
      or exists(select 1 from unnest(o.aliases) alias where lower(trim(alias))=lower(trim(coalesce(p_participant.stake_name,''))))
    )
  order by case when lower(trim(o.canonical_name))=lower(trim(coalesce(p_participant.stake_name,''))) then 0 else 1 end
  limit 1;
$$;

create or replace function public.get_origin_code_registry(p_session_id uuid)
returns table(canonical_name text, code text, aliases text[], participant_count integer)
language plpgsql
stable
security definer
set search_path=''
as $$
begin
  if not private.has_session_access(p_session_id) then raise exception 'Session access required'; end if;
  return query
  select o.canonical_name,o.code,o.aliases,
    count(p.id)::integer
  from public.origin_code_registry o
  left join public.participants p on p.session_id=o.session_id and (
    lower(trim(coalesce(p.stake_name,'')))=lower(trim(o.canonical_name))
    or exists(select 1 from unnest(o.aliases) alias where lower(trim(alias))=lower(trim(coalesce(p.stake_name,''))))
  )
  where o.session_id=p_session_id and o.active
  group by o.id,o.canonical_name,o.code,o.aliases
  order by o.canonical_name;
end;
$$;

create or replace function public.get_participant_operational_identity(p_session_id uuid)
returns table(
  participant_id uuid, fsy_id text, badge_name text, badge_state text, needs_reprint boolean,
  slot_number integer, origin_code text, company_id uuid, company_name text, group_id uuid, group_name text,
  attendance_status text, source_kind text, verification_status text, is_current boolean,
  stake_name text, unit_name text, checkin_status text, sex text, full_name text, preferred_name text,
  name_review_required boolean
)
language plpgsql
stable
security definer
set search_path=''
as $$
begin
  if not (
    private.has_capability(p_session_id,'people_lookup')
    or private.has_capability(p_session_id,'registration_view')
    or private.has_capability(p_session_id,'reports_export')
  ) then raise exception 'Your account cannot view participant operational identity'; end if;

  return query
  select p.id,b.fsy_id,b.badge_name,b.state,b.needs_reprint,b.slot_number,b.origin_code,
    c.id,c.name,g.id,g.name,coalesce(p.attendance_status,'expected'),p.source_kind,p.verification_status,p.is_current,
    p.stake_name,p.unit_name,ci.status::text,p.sex::text,
    trim(concat_ws(' ',p.first_name,p.last_name)),p.preferred_name,
    case
      when nullif(trim(coalesce(p.preferred_name,'')),'') is null then false
      when lower(trim(p.preferred_name))=lower(trim(p.first_name)) then false
      when lower(trim(p.preferred_name))=lower(trim(concat_ws(' ',p.first_name,p.last_name))) then false
      else true
    end
  from public.participants p
  left join public.participant_badge_assignments b on b.participant_id=p.id and b.session_id=p.session_id and b.state<>'retired'
  left join public.counselor_groups g on g.id=coalesce(b.group_id,p.group_id)
  left join public.companies c on c.id=coalesce(b.company_id,g.company_id)
  left join public.check_ins ci on ci.session_id=p.session_id and ci.participant_id=p.id
  where p.session_id=p_session_id
  order by c.operational_number nulls last,b.slot_number nulls last,lower(p.last_name),lower(p.first_name),p.id;
end;
$$;

create or replace function public.get_identity_readiness(p_session_id uuid)
returns table(eligible_grouped integer, active_ids integer, draft_ids integer, finalized_ids integer, unresolved_origin integer, name_reviews integer)
language plpgsql
stable
security definer
set search_path=''
as $$
begin
  if not private.has_capability(p_session_id,'registration_view') and not private.has_capability(p_session_id,'reports_export') then
    raise exception 'Registration or reporting access required';
  end if;
  return query
  with eligible as (
    select p.*, private.origin_code_for_participant(p) as origin_code
    from public.participants p
    where p.session_id=p_session_id and p.group_id is not null and private.operational_participant_is_eligible(p_session_id,p.id)
  )
  select
    (select count(*)::int from eligible),
    (select count(*)::int from public.participant_badge_assignments b where b.session_id=p_session_id and b.state<>'retired'),
    (select count(*)::int from public.participant_badge_assignments b where b.session_id=p_session_id and b.state='draft'),
    (select count(*)::int from public.participant_badge_assignments b where b.session_id=p_session_id and b.state='finalized'),
    (select count(*)::int from eligible e where e.origin_code is null),
    (select count(*)::int from eligible e where nullif(trim(coalesce(e.preferred_name,'')),'') is not null
      and lower(trim(e.preferred_name))<>lower(trim(e.first_name))
      and lower(trim(e.preferred_name))<>lower(trim(concat_ws(' ',e.first_name,e.last_name))));
end;
$$;

create or replace function public.rebuild_draft_fsy_ids(p_session_id uuid)
returns integer
language plpgsql
security definer
set search_path=''
as $$
declare inserted_count integer;
begin
  if not private.has_capability(p_session_id,'registration_manage') then raise exception 'Registration management access required'; end if;
  if exists(select 1 from public.participant_badge_assignments where session_id=p_session_id and state='finalized') then
    raise exception 'FSY IDs are already finalized. Use the vacancy/replacement workflow for day-of changes';
  end if;

  delete from public.participant_badge_assignments where session_id=p_session_id and state='draft';

  with eligible as (
    select p.id participant_id,p.session_id,p.group_id,p.sex,p.first_name,p.last_name,
      trim(concat_ws(' ',p.first_name,p.last_name)) full_name,
      g.company_id,
      coalesce(g.operational_number,nullif(regexp_replace(g.name,'\D','','g'),'')::integer) group_number,
      coalesce(c.operational_number,nullif(regexp_replace(c.name,'\D','','g'),'')::integer) company_number,
      private.origin_code_for_participant(p) origin_code
    from public.participants p
    join public.counselor_groups g on g.id=p.group_id
    join public.companies c on c.id=g.company_id
    where p.session_id=p_session_id and private.operational_participant_is_eligible(p_session_id,p.id)
  ), ranked as (
    select e.*,
      row_number() over(partition by e.company_id order by
        case when e.sex='female' then 0 else 1 end,
        e.group_number nulls last,
        lower(e.last_name),lower(e.first_name),e.participant_id
      )::integer slot_number
    from eligible e
  )
  insert into public.participant_badge_assignments(
    session_id,participant_id,company_id,group_id,slot_number,origin_code,fsy_id,badge_name,state,assigned_by
  )
  select r.session_id,r.participant_id,r.company_id,r.group_id,r.slot_number,r.origin_code,
    r.origin_code||'-C'||lpad(r.company_number::text,2,'0')||'-'||lpad(r.slot_number::text,2,'0'),
    r.full_name,'draft',(select auth.uid())
  from ranked r
  where r.origin_code is not null and r.company_number is not null;

  get diagnostics inserted_count = row_count;
  insert into public.audit_events(session_id,actor_id,action,entity_type,entity_id,metadata)
  values(p_session_id,(select auth.uid()),'fsy_ids_rebuilt','session',p_session_id::text,jsonb_build_object('draft_ids',inserted_count,'ordering','female_groups_first_then_male_groups; alphabetical within group'));
  return inserted_count;
end;
$$;

create or replace function public.finalize_fsy_ids(p_session_id uuid)
returns integer
language plpgsql
security definer
set search_path=''
as $$
declare missing_count integer; finalized_count integer;
begin
  if not private.has_capability(p_session_id,'registration_manage') then raise exception 'Registration management access required'; end if;

  select count(*)::int into missing_count
  from public.participants p
  where p.session_id=p_session_id and p.group_id is not null and private.operational_participant_is_eligible(p_session_id,p.id)
    and not exists(select 1 from public.participant_badge_assignments b where b.participant_id=p.id and b.session_id=p_session_id and b.state<>'retired');
  if missing_count>0 then raise exception '% eligible grouped participants still need an FSY ID. Resolve missing origin codes first',missing_count; end if;

  update public.participant_badge_assignments
  set state='finalized',finalized_by=(select auth.uid()),finalized_at=coalesce(finalized_at,now())
  where session_id=p_session_id and state='draft';
  get diagnostics finalized_count = row_count;

  insert into public.audit_events(session_id,actor_id,action,entity_type,entity_id,metadata)
  values(p_session_id,(select auth.uid()),'fsy_ids_finalized','session',p_session_id::text,jsonb_build_object('finalized_now',finalized_count));
  return finalized_count;
end;
$$;

create or replace function public.update_participant_badge_name(p_participant_id uuid,p_badge_name text)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare target public.participant_badge_assignments%rowtype;
begin
  select * into target from public.participant_badge_assignments where participant_id=p_participant_id and state<>'retired' for update;
  if target.id is null then raise exception 'Participant does not have an active FSY ID yet'; end if;
  if not private.has_capability(target.session_id,'registration_manage') then raise exception 'Registration management access required'; end if;
  if nullif(trim(coalesce(p_badge_name,'')),'') is null then raise exception 'Badge name is required'; end if;
  update public.participant_badge_assignments
  set badge_name=trim(p_badge_name),needs_reprint=(state='finalized')
  where id=target.id;
  insert into public.audit_events(session_id,actor_id,action,entity_type,entity_id,metadata)
  values(target.session_id,(select auth.uid()),'participant_badge_name_updated','participant',p_participant_id::text,jsonb_build_object('badge_name',trim(p_badge_name),'needs_reprint',target.state='finalized'));
end;
$$;

create or replace function public.set_participant_arrival_status(p_participant_id uuid,p_status text,p_note text default null)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare target public.participants%rowtype;
begin
  select * into target from public.participants where id=p_participant_id for update;
  if target.id is null then raise exception 'Participant not found'; end if;
  if not private.has_capability(target.session_id,'registration_manage') then raise exception 'Registration management access required'; end if;
  if p_status not in ('expected','expected_later','unknown','confirmed_not_attending') then raise exception 'Invalid arrival status'; end if;
  update public.participants set attendance_status=p_status,attendance_note=nullif(trim(coalesce(p_note,'')),''),attendance_updated_by=(select auth.uid()),attendance_updated_at=now(),updated_at=now() where id=target.id;
  insert into public.participant_arrival_events(session_id,participant_id,status,note,recorded_by)
  values(target.session_id,target.id,p_status,nullif(trim(coalesce(p_note,'')),''),(select auth.uid()));
  insert into public.audit_events(session_id,actor_id,action,entity_type,entity_id,metadata)
  values(target.session_id,(select auth.uid()),'participant_arrival_status_updated','participant',target.id::text,jsonb_build_object('status',p_status,'note',nullif(trim(coalesce(p_note,'')),'')));
end;
$$;

create or replace function public.get_arrival_reconciliation(p_session_id uuid)
returns table(
  participant_id uuid, fsy_id text, full_name text, preferred_name text, sex text, stake_name text, unit_name text,
  company_name text, group_name text, slot_number integer, attendance_status text, checkin_status text,
  source_kind text, verification_status text, is_current boolean
)
language plpgsql
stable
security definer
set search_path=''
as $$
begin
  if not private.has_capability(p_session_id,'registration_view') and not private.has_capability(p_session_id,'registration_manage') then
    raise exception 'Registration access required';
  end if;
  return query
  select p.id,b.fsy_id,trim(concat_ws(' ',p.first_name,p.last_name)),p.preferred_name,p.sex::text,p.stake_name,p.unit_name,
    c.name,g.name,b.slot_number,coalesce(p.attendance_status,'expected'),ci.status::text,p.source_kind,p.verification_status,p.is_current
  from public.participants p
  left join public.participant_badge_assignments b on b.participant_id=p.id and b.session_id=p.session_id and b.state<>'retired'
  left join public.counselor_groups g on g.id=coalesce(b.group_id,p.group_id)
  left join public.companies c on c.id=coalesce(b.company_id,g.company_id)
  left join public.check_ins ci on ci.session_id=p.session_id and ci.participant_id=p.id
  where p.session_id=p_session_id
  order by lower(coalesce(p.stake_name,'')),lower(coalesce(p.unit_name,'')),lower(p.last_name),lower(p.first_name),p.id;
end;
$$;

create or replace function public.get_arrival_vacancies(p_session_id uuid)
returns table(participant_id uuid, fsy_id text, full_name text, sex text, company_id uuid, company_name text, group_id uuid, group_name text, slot_number integer)
language plpgsql
stable
security definer
set search_path=''
as $$
begin
  if not private.has_capability(p_session_id,'registration_manage') then raise exception 'Registration management access required'; end if;
  return query
  select p.id,b.fsy_id,trim(concat_ws(' ',p.first_name,p.last_name)),p.sex::text,b.company_id,c.name,b.group_id,g.name,b.slot_number
  from public.participants p
  join public.participant_badge_assignments b on b.participant_id=p.id and b.session_id=p.session_id and b.state<>'retired'
  join public.companies c on c.id=b.company_id
  join public.counselor_groups g on g.id=b.group_id
  left join public.check_ins ci on ci.session_id=p.session_id and ci.participant_id=p.id
  where p.session_id=p_session_id and p.attendance_status='confirmed_not_attending' and coalesce(ci.status::text,'')<>'arrived'
  order by c.operational_number,b.slot_number;
end;
$$;

create or replace function public.replace_arrival_vacancy(p_absent_participant_id uuid,p_new_participant_id uuid)
returns text
language plpgsql
security definer
set search_path=''
as $$
declare absent public.participants%rowtype; newcomer public.participants%rowtype; old_badge public.participant_badge_assignments%rowtype; target_group public.counselor_groups%rowtype; target_company public.companies%rowtype; newcomer_origin text; new_fsy_id text;
begin
  select * into absent from public.participants where id=p_absent_participant_id for update;
  select * into newcomer from public.participants where id=p_new_participant_id for update;
  if absent.id is null or newcomer.id is null then raise exception 'Participant not found'; end if;
  if absent.session_id<>newcomer.session_id then raise exception 'Participants must belong to the same session'; end if;
  if not private.has_capability(absent.session_id,'registration_manage') then raise exception 'Registration management access required'; end if;
  if absent.attendance_status<>'confirmed_not_attending' then raise exception 'The original participant must first be confirmed not attending'; end if;
  if exists(select 1 from public.check_ins ci where ci.session_id=absent.session_id and ci.participant_id=absent.id and ci.status::text='arrived') then raise exception 'A participant who already checked in cannot be replaced'; end if;
  if newcomer.source_kind<>'on_site' or newcomer.verification_status<>'verified' or not newcomer.is_current then raise exception 'Choose a verified on-site participant'; end if;
  if not private.operational_participant_is_eligible(newcomer.session_id,newcomer.id) then raise exception 'The on-site participant is not operationally eligible'; end if;
  if newcomer.group_id is not null then raise exception 'The on-site participant is already assigned to a counselor group'; end if;

  select * into old_badge from public.participant_badge_assignments where participant_id=absent.id and state<>'retired' for update;
  if old_badge.id is null then raise exception 'The absent participant does not have an active roster slot'; end if;
  select * into target_group from public.counselor_groups where id=old_badge.group_id;
  select * into target_company from public.companies where id=old_badge.company_id;
  if newcomer.sex<>target_group.sex then raise exception 'The replacement participant must match the counselor group sex'; end if;
  newcomer_origin:=private.origin_code_for_participant(newcomer);
  if newcomer_origin is null then raise exception 'The on-site participant needs a recognized Stake, District, or Mission before replacement'; end if;
  new_fsy_id:=newcomer_origin||'-C'||lpad(coalesce(target_company.operational_number,nullif(regexp_replace(target_company.name,'\D','','g'),'')::integer)::text,2,'0')||'-'||lpad(old_badge.slot_number::text,2,'0');

  update public.participant_badge_assignments set state='retired',retired_by=(select auth.uid()),retired_at=now(),note='Retired when roster slot was filled by an on-site participant' where id=old_badge.id;
  update public.participants set group_id=null,attendance_status='confirmed_not_attending',updated_at=now() where id=absent.id;
  update public.participants set group_id=old_badge.group_id,attendance_status='expected',attendance_note=null,attendance_updated_by=(select auth.uid()),attendance_updated_at=now(),updated_at=now() where id=newcomer.id;

  insert into public.participant_badge_assignments(session_id,participant_id,company_id,group_id,slot_number,origin_code,fsy_id,badge_name,state,replacement_for,assigned_by,finalized_by,finalized_at)
  values(newcomer.session_id,newcomer.id,old_badge.company_id,old_badge.group_id,old_badge.slot_number,newcomer_origin,new_fsy_id,trim(concat_ws(' ',newcomer.first_name,newcomer.last_name)),'finalized',old_badge.id,(select auth.uid()),(select auth.uid()),now());

  insert into public.participant_arrival_events(session_id,participant_id,status,note,recorded_by)
  values(absent.session_id,absent.id,'replaced','Roster slot filled by on-site participant',(select auth.uid()));
  insert into public.audit_events(session_id,actor_id,action,entity_type,entity_id,metadata)
  values(absent.session_id,(select auth.uid()),'arrival_vacancy_replaced','participant',newcomer.id::text,jsonb_build_object('replaced_participant_id',absent.id,'company_id',old_badge.company_id,'group_id',old_badge.group_id,'slot_number',old_badge.slot_number,'fsy_id',new_fsy_id));
  return new_fsy_id;
end;
$$;

-- Leadership permissions v2: Session Directing Couple, Logistical Admin, and Coordinator all receive full session operations.
create or replace function private.effective_capabilities(target_session uuid, target_user uuid default null)
returns text[]
language sql
stable
security definer
set search_path=''
as $$
with subject as (select coalesce(target_user,(select auth.uid())) user_id), base as (
  select unnest(case
    when aa.role in ('session_director','logistics_admin','coordinator') then array[
      'people_lookup','groups_view','checkin_record','headcount_view','headcount_record',
      'registration_view','registration_manage','identity_manage','arrival_manage',
      'staff_view','staff_manage','housing_view','housing_manage','housing_export',
      'food_view','food_manage','food_export','wellness_status','wellness_private','wellness_manage',
      'inclusion_view','facilities_view','materials_view','financial_view','publicity_view',
      'reports_export','access_admin'
    ]::text[]
    when aa.role='assistant_coordinator' then array['people_lookup','groups_view','checkin_record','headcount_view','headcount_record']::text[]
    else '{}'::text[] end) capability
  from public.access_assignments aa,subject s where aa.session_id=target_session and aa.user_id=s.user_id and aa.active
), explicit_caps as (
  select unnest(aa.capabilities) capability from public.access_assignments aa,subject s where aa.session_id=target_session and aa.user_id=s.user_id and aa.active
), team_caps as (
  select unnest(ot.capabilities) capability from public.team_memberships tm join public.operational_teams ot on ot.id=tm.team_id join subject s on s.user_id=tm.user_id where tm.session_id=target_session and tm.active and ot.active
)
select coalesce(array_agg(distinct capability order by capability),'{}'::text[])
from (select capability from base union all select capability from explicit_caps union all select capability from team_caps) caps
where capability is not null;
$$;

update public.operational_teams
set capabilities=(select array_agg(distinct capability order by capability) from unnest(capabilities||array['identity_manage','arrival_manage']::text[]) capability),updated_at=now()
where team_key in ('registration','logistics');

create or replace function private.can_manage_access(target_session uuid)
returns boolean
language sql
stable
security definer
set search_path=''
as $$
  select exists(select 1 from public.access_assignments aa where aa.session_id=target_session and aa.user_id=(select auth.uid()) and aa.active and aa.role in ('coordinator','logistics_admin','session_director'));
$$;

create or replace function private.is_top_access_admin(target_session uuid)
returns boolean
language sql
stable
security definer
set search_path=''
as $$
  select exists(select 1 from public.access_assignments aa where aa.session_id=target_session and aa.user_id=(select auth.uid()) and aa.active and aa.role in ('coordinator','logistics_admin','session_director'));
$$;

-- Registration-team permissions must be honored by server RPCs, not only by navigation.
create or replace function public.record_participant_checkin(p_session_id uuid,p_participant_id uuid,p_status public.check_in_status,p_note text default null)
returns void
language plpgsql
security definer
set search_path=''
as $$
begin
  if not (
    private.has_capability(p_session_id,'checkin_record')
    or exists(select 1 from public.participants p join public.counselor_groups g on g.id=p.group_id where p.id=p_participant_id and p.session_id=p_session_id and private.can_access_company(p_session_id,g.company_id))
  ) then raise exception 'Your account cannot record check-in for this participant'; end if;
  if not private.operational_participant_is_eligible(p_session_id,p_participant_id) then raise exception 'This record is outside the current youth operational eligibility rules'; end if;
  if exists(select 1 from public.counselor_groups g where g.session_id=p_session_id and g.state='published') and not exists(select 1 from public.participants p where p.id=p_participant_id and p.session_id=p_session_id and p.group_id is not null) then raise exception 'Participant still needs a counselor group assignment'; end if;
  insert into public.check_ins(session_id,participant_id,status,note,recorded_by,recorded_at)
  values(p_session_id,p_participant_id,p_status,nullif(trim(coalesce(p_note,'')),''),(select auth.uid()),now())
  on conflict(session_id,participant_id) do update set status=excluded.status,note=excluded.note,recorded_by=excluded.recorded_by,recorded_at=excluded.recorded_at;
  insert into public.audit_events(session_id,actor_id,action,entity_type,entity_id,metadata)
  values(p_session_id,(select auth.uid()),'participant_checkin_recorded','participant',p_participant_id::text,jsonb_build_object('status',p_status));
end;
$$;

create or replace function public.verify_on_site_participant(p_participant_id uuid,p_approved boolean,p_note text default null)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare target public.participants%rowtype;
begin
  select * into target from public.participants where id=p_participant_id for update;
  if target.id is null or target.source_kind<>'on_site' then raise exception 'On-site participant not found'; end if;
  if not private.has_capability(target.session_id,'registration_manage') then raise exception 'Registration management access required'; end if;
  update public.participants set verification_status=case when p_approved then 'verified' else 'rejected' end,is_current=p_approved,verified_by=(select auth.uid()),verified_at=now(),updated_at=now() where id=target.id;
  insert into public.audit_events(session_id,actor_id,action,entity_type,entity_id,metadata)
  values(target.session_id,(select auth.uid()),case when p_approved then 'on_site_participant_verified' else 'on_site_participant_rejected' end,'participant',target.id::text,jsonb_build_object('note',nullif(trim(coalesce(p_note,'')),'')));
end;
$$;

create or replace function public.assign_participant_to_group(p_participant_id uuid,p_group_id uuid)
returns void
language plpgsql
security definer
set search_path=''
as $$
declare target public.participants%rowtype; target_group public.counselor_groups%rowtype; max_size integer; avoid_units boolean;
begin
  select * into target from public.participants where id=p_participant_id for update;
  select * into target_group from public.counselor_groups where id=p_group_id;
  if target.id is null or target_group.id is null or target.session_id<>target_group.session_id then raise exception 'Participant and group must belong to the same session'; end if;
  if not (private.has_capability(target.session_id,'registration_manage') or private.has_capability(target.session_id,'staff_manage')) then raise exception 'Your account cannot assign participants'; end if;
  if not private.operational_participant_is_eligible(target.session_id,target.id) then raise exception 'This record is not currently eligible for youth operations. Review registration status, verification and age first'; end if;
  if target.sex<>target_group.sex then raise exception 'Participant sex does not match the selected group'; end if;
  select group_max_size,avoid_same_unit into max_size,avoid_units from public.session_structure_settings where session_id=target.session_id;
  max_size:=coalesce(max_size,10); avoid_units:=coalesce(avoid_units,true);
  if (select count(*) from public.participants p where p.group_id=target_group.id and p.id<>target.id and private.operational_participant_is_eligible(target.session_id,p.id))>=max_size then raise exception 'This counselor group is already at its configured maximum size'; end if;
  if avoid_units and exists(select 1 from public.participants peer where peer.group_id=target_group.id and peer.id<>target.id and private.operational_participant_is_eligible(target.session_id,peer.id) and lower(trim(peer.unit_name))=lower(trim(target.unit_name))) then raise exception 'This group already contains someone from the same unit'; end if;
  update public.participants set group_id=target_group.id,updated_at=now() where id=target.id;
  insert into public.audit_events(session_id,actor_id,action,entity_type,entity_id,metadata)
  values(target.session_id,(select auth.uid()),'participant_group_assigned','participant',target.id::text,jsonb_build_object('group_id',target_group.id));
end;
$$;

create or replace function public.add_on_site_participant_v2(
  p_session_id uuid,p_first_name text,p_last_name text,p_preferred_name text,p_sex public.participant_sex,p_date_of_birth date,p_unit_name text,
  p_stake_name text default null,p_phone text default null,p_contact_name text default null,p_contact_phone text default null,p_tshirt_size text default null,
  p_medical_information text default null,p_dietary_information text default null,p_search_confirmed boolean default false
)
returns uuid
language plpgsql
security definer
set search_path=''
as $$
declare next_id uuid:=extensions.gen_random_uuid(); session_start date; calculated_age integer;
begin
  if not private.has_capability(p_session_id,'registration_manage') then raise exception 'Registration management access required'; end if;
  if not p_search_confirmed then raise exception 'Search the existing registration list before adding someone'; end if;
  select starts_on into session_start from public.sessions where id=p_session_id;
  if session_start is null then raise exception 'Session start date is required'; end if;
  if p_date_of_birth is null or p_date_of_birth>session_start then raise exception 'A valid date of birth is required'; end if;
  calculated_age:=extract(year from age(session_start,p_date_of_birth))::integer;
  if nullif(trim(coalesce(p_first_name,'')),'') is null or nullif(trim(coalesce(p_last_name,'')),'') is null or nullif(trim(coalesce(p_unit_name,'')),'') is null or calculated_age not between 1 and 120 then raise exception 'Name, date of birth, sex, and ward or branch are required'; end if;
  if nullif(trim(coalesce(p_phone,'')),'') is null and nullif(trim(coalesce(p_contact_phone,'')),'') is null then raise exception 'Add the participant phone or a parent/guardian phone number'; end if;
  if exists(select 1 from public.participants participant join public.participant_private_details details on details.participant_id=participant.id where participant.session_id=p_session_id and participant.is_current and lower(trim(participant.first_name))=lower(trim(p_first_name)) and lower(trim(participant.last_name))=lower(trim(p_last_name)) and details.date_of_birth=p_date_of_birth) then raise exception 'A person with this name and date of birth is already in the session. Search again before adding'; end if;
  insert into public.participants(id,session_id,registration_id,first_name,last_name,preferred_name,sex,age,unit_name,stake_name,source_kind,registration_status,verification_status,is_current,reconciliation_status,attendance_status)
  values(next_id,p_session_id,'ONSITE-'||upper(substr(replace(next_id::text,'-',''),1,12)),trim(p_first_name),trim(p_last_name),nullif(trim(coalesce(p_preferred_name,'')),''),p_sex,calculated_age,trim(p_unit_name),nullif(trim(coalesce(p_stake_name,'')),''),'on_site','approved','pending',true,'current','expected');
  insert into public.participant_private_details(participant_id,session_id,date_of_birth,phone,contact_1_name,contact_1_phone,tshirt_size,medical_information,dietary_information,updated_at)
  values(next_id,p_session_id,p_date_of_birth,nullif(trim(coalesce(p_phone,'')),''),nullif(trim(coalesce(p_contact_name,'')),''),nullif(trim(coalesce(p_contact_phone,'')),''),nullif(trim(coalesce(p_tshirt_size,'')),''),nullif(trim(coalesce(p_medical_information,'')),''),nullif(trim(coalesce(p_dietary_information,'')),''),now());
  insert into public.audit_events(session_id,actor_id,action,entity_type,entity_id,metadata)
  values(p_session_id,(select auth.uid()),'on_site_participant_added_v2','participant',next_id::text,jsonb_build_object('age_at_session_start',calculated_age,'unit_name',trim(p_unit_name),'has_contact',true));
  return next_id;
end;
$$;

revoke all on function public.get_origin_code_registry(uuid) from public, anon;
revoke all on function public.get_participant_operational_identity(uuid) from public, anon;
revoke all on function public.get_identity_readiness(uuid) from public, anon;
revoke all on function public.rebuild_draft_fsy_ids(uuid) from public, anon;
revoke all on function public.finalize_fsy_ids(uuid) from public, anon;
revoke all on function public.update_participant_badge_name(uuid,text) from public, anon;
revoke all on function public.set_participant_arrival_status(uuid,text,text) from public, anon;
revoke all on function public.get_arrival_reconciliation(uuid) from public, anon;
revoke all on function public.get_arrival_vacancies(uuid) from public, anon;
revoke all on function public.replace_arrival_vacancy(uuid,uuid) from public, anon;
grant execute on function public.get_origin_code_registry(uuid) to authenticated;
grant execute on function public.get_participant_operational_identity(uuid) to authenticated;
grant execute on function public.get_identity_readiness(uuid) to authenticated;
grant execute on function public.rebuild_draft_fsy_ids(uuid) to authenticated;
grant execute on function public.finalize_fsy_ids(uuid) to authenticated;
grant execute on function public.update_participant_badge_name(uuid,text) to authenticated;
grant execute on function public.set_participant_arrival_status(uuid,text,text) to authenticated;
grant execute on function public.get_arrival_reconciliation(uuid) to authenticated;
grant execute on function public.get_arrival_vacancies(uuid) to authenticated;
grant execute on function public.replace_arrival_vacancy(uuid,uuid) to authenticated;
